### ISSUE TITLE
Midazolam

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#100]
Following discussion in #98  as a pragmatic solution we are going to identify all those prescribed midazolam - end of life is the only indication that is used widely for in primary care.

**Comment by brianmackenna** [comment]
@richiecroker what do you think?

https://codelists.opensafely.org/codelist/opensafely/midazolam/652aafbe/

**Comment by richiecroker** [comment]
I'd be included *not* to include the high strength infusion vials 
| code | term |
| --- | --- |
| 1501041T0AAACAC | Midazolam 50mg/50ml solution for infusion vials |
| 1501041T0AAANAN | Midazolam 50mg/10ml solution for injection ampoules |
| 1501041T0AAARAR | Midazolam 100mg/50ml solution for infusion vials |

apart from that, i'm happy.

**Comment by brianmackenna** [comment]
Any idea what they are being used for?

https://openprescribing.net/analyse/#org=stp&numIds=1501041T0AAARAR,1501041T0AAANAN,1501041T0AAACAC&denom=nothing&selectedTab=summary

**Comment by brianmackenna** [comment]
After furtehr discussion and research we think that the infusion vials may be used in exceptional circumstances or in rare situations where other preps aren't available. We will include for purposes of this list

**Comment by brianmackenna** [comment]
@richiecroker dm+d list for checking

https://codelists.opensafely.org/codelist/opensafely/midazolam-end-of-life/4c1b3c89/#full-list

**Comment by richiecroker** [comment]
checked, signed off and published.
