### ISSUE TITLE
Learning Disability

### ISSUE THREAD

**Issue by orlamac** [opensafely/codelist-development#112]
This is where we discuss the development of a code list to identify those with Learning Disabilities in NHS care.  

The following document will be used as a reference...

[https://www.england.nhs.uk/wp-content/uploads/2019/10/improving-identification-of-people-with-a-learning-disability-guidance-for-general-practice.pdf](url)

It is noted that the SNOMED list for intellectual disabilities contains a wide variety of diagnosis that are not included in the above reference and some that are included in Appendix 2 of the above reference (i.e. not always indicative of a learning disability).  We must choose whether we pick out only those included in Appendix 1 of the above reference and exclude the rest, or whether we include all of the diagnosis listed in SNOMED under intellectual disability, except for those found in Appendix 2 of the above reference.

**Comment by brianmackenna** [comment]
It's not clear to me from this documentation why we need another codelist. There are already [5 codelists on OpenCodelists](https://codelists.opensafely.org/?q=learning+disability) as well as  [NHS Digital lists related to autism and learning disability](https://codelists.opensafely.org/codelist/nhsd-primary-care-domain-refsets/). Are they not sufficient?

**Comment by orlamac** [comment]
My misunderstanding - I thought you wanted to generate a new code list specifically for this task, but I agree that we should preferably use those that are already in place.  I have no further information or data to warrant developing a new codelist.  I would suggest that the NHS Digital list LD_COD would be most appropriate for our search as they appear to be up to date with reference to the NHS digital document referenced above.  However I'm curious to know why separate LD codelists were created using CTV3 codes last year, rather than using the LD_COD list.

**Comment by brianmackenna** [comment]
When we started OpenSAFELY we used CTV3 codelists and there were no openly available codelists from NHSD. SNOMED functionality was added at a later date and we are now able to import NHSD codelists
