### ISSUE TITLE
First generation antipsychotics, excluding long acting depots

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#114]
Separated discussion from #111 

https://codelists.opensafely.org/codelist/user/orlamac/first-generation-antipsychotics-excluding-long-acting-depots/1caf1615/

codelist looks good, just needs conversion to dm+d.

Nit on the the documentation - worth saying it is BNF codes `0402` For example [Loxapine is in the BNF](https://bnf.nice.org.uk/drug/loxapine.html) but not in the codes as hasn't been dispensed in last five years

**Comment by orlamac** [comment]
I have updated the codelist to make it clear in the description that the injectable formulations of levomepromazine are not included.  These are only used in palliative care.  Levomepromazine tablets may be used for psychotic disorders.

**Comment by orlamac** [comment]
We will develop a separate codelist for haloperidol (see <https://github.com/opensafely/codelist-development/issues/128>)
to further explore unusual prescribing trends during the pandemic, however we will leave haloperidol in this FGA codelist as well.  

As mentioned in previous documentation, this codelist contains all first generation antipsychotics **except for** 

- long acting depot formulations of FGAs (see <https://github.com/opensafely/codelist-development/issues/111>)
- droperidol (which is only used for post operative nausea and vomiting), 
- injectable formulations of levomepromazine (which are only used for palliative care) 
- all prochlorperazine formulations (developed as a separate codelist see <https://github.com/opensafely/codelist-development/issues/113>)

@brianmackenna and @richiecroker could you please review and approve this codelist?

**Comment by richiecroker** [comment]
checked and approved.  If you could publish and create dm+d version that'd be great thanks.

**Comment by orlamac** [comment]
<https://www.opencodelists.org/codelist/opensafely/first-generation-antipsychotics-excluding-long-acting-depots-dmd/1e9b227c/>
