### ISSUE TITLE
Second generation antipsychotics, excluding long acting injection

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#116]
Seperated from #111  for discussion

https://codelists.opensafely.org/codelist/user/orlamac/second-generation-antipsychotics-excluding-long-acting-injections/38714940/

@orlamac Is loxapine not a first generation antipsychotic? See  #114

Same comments about snomed refset link as #115

**Comment by brianmackenna** [comment]
I'm tempted as rferences including BNF call it first generation to put there HOWEVER not been dispensed so lets not spend time on it. @orlamac you make final decision as your area of expertise!

**Comment by orlamac** [comment]
Agreed.  Let's call it first generation.  I will update the codelists.

**Comment by orlamac** [comment]
Codelist has been updated - Loxapine has been removed.

**Comment by orlamac** [comment]
@brianmackenna or @richiecroker could you please review and approve this codelist?

**Comment by richiecroker** [comment]
@orlamac a tiny thing (hardly any prescribing), but I note that asenapine is included in the codelist.  I know technically second generation, but only licensed for mania?

**Comment by richiecroker** [comment]
Also loxapine still in second generation codelist?

**Comment by richiecroker** [comment]
apart from two queries above, checked.

**Comment by orlamac** [comment]
Thanks for checking these Rich.  I have updated the metadata to highlight that asenapine is only licensed to treat mania.  I've done this for the original and the DM&D versions.  I've checked and Loxapine is not included in the second gen list.

**Comment by orlamac** [comment]
DM&D version 
`https://www.opencodelists.org/codelist/opensafely/second-generation-antipsychotics-excluding-long-acting-injections/6c7c3c11/`

**Comment by richiecroker** [comment]
![image](https://user-images.githubusercontent.com/18683239/123705243-9861be00-d85e-11eb-983d-f89ccd2fbe5f.png)
Hi @orlamac i've just had another look, and this is on there

**Comment by orlamac** [comment]
Fab!  Thanks Rich.

**Comment by richiecroker** [comment]
checked and signed off
