### ISSUE TITLE
Haloperidol

### ISSUE THREAD

**Issue by orlamac** [opensafely/codelist-development#128]
We have opened a new codelist for haloperidol in order to explore unusual trends in antipsychotic prescribing during the first few months of the Covid 19 pandemic.  
This codelist will contain all formulations of haloperidol, except for the haloperidol decanoate which is the long acting depot formulation.   
<https://www.opencodelists.org/codelist/opensafely/haloperidol/3427b92f/>

**Comment by orlamac** [comment]
While exploring trends in antipsychotic prescribing during the pandemic we observed a spike in antipsychotic prescribing in care homes and in patients with dementia during the first three months of the pandemic.  We wanted to check if this spike could be related to haloperidol which is often used in palliative care.   
Haloperidol is also used for short term management of aggression and agitation in the context of psychiatric disorders, including dementia.

**Comment by orlamac** [comment]
@brianmackenna or @richiecroker could you please review and approve this codelist when you get a chance?

**Comment by richiecroker** [comment]
i'll take a look @orlamac

**Comment by richiecroker** [comment]
@orlamac approved.  Can you create a dm+d version please.

**Comment by orlamac** [comment]
Will do.  Thanks Rich.

**Comment by orlamac** [comment]
Please see haloperidol dm&d version:
<https://www.opencodelists.org/codelist/opensafely/haloperidol-dmd/0893ab89/>
@richiecroker or @brianmackenna could you please review?  Many thanks

**Comment by richiecroker** [comment]
@orlamac these look like BNF codes to me, rather than dm+d codes

**Comment by richiecroker** [comment]
have checked and signed off
