### ISSUE TITLE
Cephalosporins, macrolides, metronidazole tinidazole & ornidazole, penicillins, quinolones, sulphonamides & trimethoprim, tetracyclines and drugs for urinary-tract infections

### ISSUE THREAD

**Issue by Jongmassey** [opensafely/codelist-development#134]
https://www.opencodelists.org/codelist/user/jon_massey/cephalosporins-macrolides-metronidazole-tinidazole-ornidazole-penicillins-quinolones-sulphonamides-trimethoprim-tetracyclines-and-drugs-for-urinary-tract-infections/135eab61/

Taken from denominator SQL for [definition](https://openprescribing.net/measure/ktt9_cephalosporins/definition/) of [Antibiotic stewardship: co-amoxiclav, cephalosporins & quinolones (KTT9) measure](https://openprescribing.net/measure/ktt9_cephalosporins/) on [OpenPrescribing](https://openprescribing.net/)

I'm open to suggestions of more concise names for this list!

**Comment by Jongmassey** [comment]
@inglesp Can I just check that I've not missed this one amongst the migrated openprescribing.net codelists on opencodelists.org?

**Comment by inglesp** [comment]
Isn't it this one? https://www.opencodelists.org/codelist/openprescribing/co-amoxiclav-cephalosporins-and-quinolones/392e93d2/

**Comment by Jongmassey** [comment]
That's the numerator - I'm looking for the denominator

**Comment by inglesp** [comment]
Looks like it got missed out, sorry.  How urgent is it to import it?

**Comment by Jongmassey** [comment]
I've recreated it in the list linked in the first comment - could you pass your expert eye over it so make sure I've not made any errors?

**Comment by Jongmassey** [comment]
Agreed with @richiecroker and @brianmackenna  to use the "all antibacterials" list instead and not port this denominator list.
