### ISSUE TITLE
*MEDICINE* - Hyoscine Butylbromide - Palliative Formulations

### ISSUE THREAD

**Issue by a-d-brown** [opensafely/codelist-development#213]
### User Requirements
This codelist aims to identify Hyoscine Butylbromide being used in the context of palliative care. Typically this is as a subcutaneous formulation, as detailed in [Scottish Palliative Care Guidelines](https://www.palliativecareguidelines.scot.nhs.uk/guidelines/end-of-life-care/care-in-the-last-days-of-life.aspx).

### Search Terms
- Hyoscine Butylbromide

### Inclusion Criteria for Codes
- Refers to Hyoscine Butylbromide

### Exclusion Criteria for Codes
- Refers to a Hyoscine Butylbromide formulation which is not subcutaneous (this is unlikely to be palliative indication).

### Borderline Cases to Highlight
- None

### Codelist: https://www.opencodelists.org/codelist/user/Andrew/hyoscine-butylbromide-subcutaneous-formulations/3188569a/

@brianmackenna @richiecroker

**Comment by richiecroker** [comment]
@a-d-brown as discussed, can we find out why they have selected only butylbromide, as opposed to hydrobromide formulations please.

**Comment by richiecroker** [comment]
@a-d-brown happy with this codelist.

**Comment by a-d-brown** [comment]
@richiecroker great, dm+d version uploaded here:
https://www.opencodelists.org/codelist/opensafely/hyoscine-butylbromide-subcutaneous-formulations/252fefa4/

Do I need to click the 'publish' button, and if so am I ok to do that without any further approvals? Or is it good practice for you to also check the dm+d version looks ok first before it is published?

**Comment by richiecroker** [comment]
Let's discuss at the meeting today @a-d-brown , i've published this one for now.
