### ISSUE TITLE
*MEDICINE* - Levomepromazine - Palliative Formulations

### ISSUE THREAD

**Issue by a-d-brown** [opensafely/codelist-development#214]
### User Requirements
This codelist aims to identify Levomepromazine being used in the context of palliative care. This is typically subcutaneous formulations, but can also include other formulations at a oral dose of up to 25mg - as detailed in [BNF](https://bnf.nice.org.uk/drug/levomepromazine.html#indicationsAndDoses), [Scottish Palliative Care Guidelines](https://www.palliativecareguidelines.scot.nhs.uk/guidelines/medicine-information-sheets/levomepromazine.aspx#:~:text=Levomepromazine%20is%20a%20phenothiazine%20used,the%20last%20days%20of%20life.) and [Greater Manchester Palliative Care Guidelines](https://www.england.nhs.uk/north-west/wp-content/uploads/sites/48/2020/01/Palliative-Care-Pain-and-Symptom-Control-Guidelines.pdf).

### Search Terms
- Levomepromazine 

### Inclusion Criteria for Codes
- Refers to Levomepromazine 

### Exclusion Criteria for Codes
- Refers to a Levomepromazine formulation which is more likely to be used for an indication unrelated to palliative care.

### Borderline Cases to Highlight
- Levomepromazine 50mg tablets.
_Excluded on the basis that this formulation is also licenced for schizophrenia and is less likely to be used for its palliative care indications due its high strength._

### Codelist: https://www.opencodelists.org/codelist/user/Andrew/levomepromazine-oral-subcutaneous/7f69702f/

@brianmackenna @richiecroker

**Comment by a-d-brown** [comment]
Amended to remove oral formulations after reflection that these were unlikely to be consistently related to palliative indications.

Uploaded dm+d version here: https://www.opencodelists.org/codelist/opensafely/levomepromazine-subcutaneous/40f222cf/

**Comment by richiecroker** [comment]
Published
