### ISSUE TITLE
*MEDICINE* - Oxycodone SC - Palliative

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#215]
### User Requirements
This code list aims to identify oxycodone being used in the context of palliative care.
Medications and routes/formulations are based on [Priority medicines for palliative and end of life care during
a pandemic](https://apmonline.org/wp-content/uploads/2020/04/priority-meds-for-end-of-life-care-290420-final-2.pdf).
This list covers formulations that could be given subcutaneously.
An initial draft list was created by user (https://www.opencodelists.org/codelist/user/eiliskeeble/oxycodone/72b263f0/)
It was subsequently agreed to focus only on the SC route to better identify prescribing for palliative care.

### Search Terms

- Oxycodone

### Inclusion Criteria for Codes

- Refers to oxycodone formulations that could be given subcutaneously.

### Exclusion Criteria for Codes

- Oxycodone formulations that are not for SC route (e.g. PO/suppositories)

### Borderline Cases to Highlight

- N/A

### Codelist: https://www.opencodelists.org/codelist/user/chriswood/oxycodone-subcutaneous/362722f7/

**Comment by chrisjwood16** [comment]
Update code list created to focus only on SC oxycodone to better identify prescribing for palliative care.

**Comment by richiecroker** [comment]
@chrisjwood16 I am happy with this codelist.

**Comment by chrisjwood16** [comment]
Final dm+d format - https://www.opencodelists.org/codelist/opensafely/oxycodone-subcutaneous-dmd/2a956f90/ @richiecroker

**Comment by richiecroker** [comment]
published
