### ISSUE TITLE
*MEDICINE* - Morphine SC - Palliative

### ISSUE THREAD

**Issue by speed-vm** [opensafely/codelist-development#218]
### **User Requirements**
This codelist aims to identify morphine being used in the context of palliative care at the end of life.
Medications and routes/formulations are based on [(https://apmonline.org/wp-content/uploads/2020/04/priority-meds-for-end-of-life-care-290420-final-2.pdf)](https://apmonline.org/wp-content/uploads/2020/04/priority-meds-for-end-of-life-care-290420-final-2.pdf)
This list covers formulations that could be given subcutaneously **only**.

An initial draft list was created by user (https://www.opencodelists.org/codelist/user/eiliskeeble/morphine/0bc1d726/
(All formulation considered in this initial draft list)

**Search Terms**
Morphine

**Inclusion Criteria for Codes**
Refers to morphine formulations that could be given subcutaneously.

**Exclusion Criteria for Codes**
Morphine formulations that are not for SC route (e.g. PO,suppositories / topical)
Diamorphine
Apomorphine
Morphine sulphate infusion bags
Morphine hydrochloride (no products available)

**Borderline Cases to Highlight**
Morphine and cyclizine exists in combination, have not included.

Codelist: https://www.opencodelists.org/codelist/user/speed-vm/medicine-morphine-sc-palliative/1d17afc2/

Updated codelist UDVs removed:
Codelist: https://www.opencodelists.org/codelist/user/speed-vm/medicine-morphine-sc-palliative/3b8ca2e3/###

**Comment by richiecroker** [comment]
@speed-vm happy with this codelist now.

**Comment by chrisjwood16** [comment]
Converted to dm+d codelist: https://www.opencodelists.org/codelist/opensafely/morphine-subcutaneous-dmd/1185fc5b/ @richiecroker

**Comment by richiecroker** [comment]
Published
