### ISSUE TITLE
*MEDICINE* - Haloperidol SC - Palliative

### ISSUE THREAD

**Issue by speed-vm** [opensafely/codelist-development#219]
**User Requirements**
This codelist aims to identify haloperidol being used in the context of palliative care at the end of life. Medications are based on [[Priority medicines for palliative and end of life care during a pandemic.](https://apmonline.org/wp-content/uploads/2020/04/priority-meds-for-end-of-life-care-290420-final-2.pdf)]

This list covers formulations that could be given subcutaneously.

**Methodology**
Search Terms 
Haloperidol

**Inclusion Criteria for Codes**

Refers to haloperidol formulations that could be given subcutaneously.

**Exclusion Criteria for Codes**

Haloperidol formulations that are not for SC route (e.g. PO, depo injection including haloperidol decanoate)

**Borderline Cases to Highlight** 
Nil

First codelist: https://www.opencodelists.org/codelist/user/speed-vm/medicine-haloperidol-sc-palliative/04083c8d/###

Updated codelist without 20mg/2ml because it has not been prescribed for years : https://www.opencodelists.org/codelist/user/speed-vm/medicine-haloperidol-sc-palliative/549c1618/

**Comment by richiecroker** [comment]
@speed-vm I am happy with this codelist.  I wonder whether 20mg/2ml would be used in palliative care, but I note there has been no prescribing for years.

**Comment by speed-vm** [comment]
@richiecroker 20mg/2ml removed as discussed, link updated above

**Comment by richiecroker** [comment]
@speed-vm happy with the codelist.

**Comment by chrisjwood16** [comment]
Converted to dm+d codelist: https://www.opencodelists.org/codelist/opensafely/haloperidol-subcutaneous-dmd/78768925/
@richiecroker

**Comment by richiecroker** [comment]
Published
