### ISSUE TITLE
*MEDICINE* - Diamorphine SC - Palliative

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#220]
### User Requirements
This codelist aims to identify diamorphine being used in the context of palliative care.

### Search Terms

- Diamorphine

### Inclusion Criteria for Codes

- Diamorphine for SC route

### Exclusion Criteria for Codes

- Diamorphine formulations that are not for SC route.

### Borderline Cases to Highlight

- Very high strength diamorphine injections (e.g. 100mg/500mg injection)
_I have included these within the code list for completeness - no other obvious indication these would be used for - there does seem to be some ongoing regular prescribing of 100mg injection._

### Codelist: https://www.opencodelists.org/codelist/user/chriswood/diamorphine-sc/6dab894d

**Comment by richiecroker** [comment]
@chrisjwood16 I agree with the codelist, I have certainly seen palliative care patients getting very high doses of diamorphine, so agree these should be included in the codelist - especially as these patients are unable to have high dose morphine sulfate without multiple syringe drivers.

**Comment by richiecroker** [comment]
Published
