### ISSUE TITLE
*MEDICINE* Hyoscine hydrobromide SC - Palliative

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#221]
### User Requirements
This codelist aims to identify hyoscine hydrobromide being used in the context of palliative care by subcutaneous route.

### Search Terms

- Hyoscine hydrobromide
- Hyoscine

### Inclusion Criteria for Codes

- Hyoscine hydrobromide for SC route

### Exclusion Criteria for Codes

- Hyoscine hydrobromide formulations that are not for SC route.
- Combination products with other active drugs (Papaveretum 15.4mg/Hyoscine hydrobrom 400microg/1ml inj amp)

### Borderline Cases to Highlight

- N/A

### Codelist: https://www.opencodelists.org/codelist/user/chriswood/hyoscine-hydrobromide-sc/096dbc79

**Comment by richiecroker** [comment]
@chrisjwood16 agree with the codelist.

**Comment by richiecroker** [comment]
Published
