### ISSUE TITLE
* CONDITION * Advanced Decompensated Cirrhosis

### ISSUE THREAD

**Issue by lshbz1** [opensafely/codelist-development#226]
We will create a list of diagnoses of advanced decompensated cirrhosis, which is a contraindication of Paxlovid for non-hospitalised COVID-19 patients.

**Comment by speed-vm** [comment]
@lshbz1 hello! I am assigned to help codelists for advanced decompensated cirrhosis and ascitic drains. 

Just seeing comment above, are you going to provide a list of diagnoses on which I should base codelist or are you starting one yourself?

Thank you

**Comment by lshbz1** [comment]
Hi Vicky, sorry for the confusion, only need a codelist (both snomed and icd) for one diagnosis (advanced decompensated cirrhosis) but it may have different terminology...

**Comment by speed-vm** [comment]
**Description
User Requirements**
Codelist to identify patients with advanced decompensated cirrhosis. 

**Methodology**
Search Terms:
Cirrhosis
Cirrhosis of the liver
Decompensated
Decompensated liver
Child pugh C
Ascites
Oesophageal varices
Portal Hypertension
Hepatic encephalopathy

**Inclusion Criteria for Codes**
Codes indicating decompensated cirrhosis, including jaundice, ascites, hepatic encephalopathy, hepatorenal syndrome or variceal haemorrhage (portal hypertension).
?consider rifaximin as a medicine proxy

**Exclusion Criteria for Codes**

**Borderline Cases to Highlight:**

First codelist: TBD

@lshbz1 I'm just looking at what to include/exclude in the list. What do you think about the above in terms of inclusion criteria. I think it depends on the ultimate use of the code and how inclusive you wish to be? My main concern is that you aren't going to identify patients that have _advanced decompensation_ 

If you are happy, I will go ahead with the above, but would be grateful for your thoughts before I go ahead!

Refs:
https://www.bsg.org.uk/wp-content/uploads/2020/08/[Cirrhosis-discharge-bundle-long-V1.1-BSG-BASL-25-08-2020.pdf](https://www.bsg.org.uk/wp-content/uploads/2020/08/Cirrhosis-discharge-bundle-long-V1.1-BSG-BASL-25-08-2020.pdf)

Mansour D, McPherson S. Management of decompensated cirrhosis. Clin Med (Lond). 2018;18(Suppl 2):s60-s65. doi:10.7861/clinmedicine.18-2-s60

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6334027/pdf/clinmed-18-2s-s60.pdf

**Comment by lshbz1** [comment]
Hi Vicky, I agree with the inclusion criteria. I also did a quick search for Snomed codes and didn't find exact match of the term "advanced decompensated cirrhosis", so the broad definition is needed. This codelist will be mainly used for identifying and excluding patients that shouldn't be prescribed Paxlovid. rifaximin seems reasonable but it's already included in the Paxlovid Drug Interactions codelist, so maybe we don't need to include it here. Many thanks for your help!

**Comment by speed-vm** [comment]
Hi @lshbz1, have made some progress with the code list SNOMED today, I will share with the team for comments and review.

_SNOMED hierachy background comment_
Decompensated cirrhosis of the liver as a SNOMED term is a child to parents _Hepatic Failure_ and _Cirrhosis of the Liver.
All relevant terms from 'child terms' from these two parents have been included as well as the conditions indicative of decompensated liver disease including codes for ascites, hepatic encephalopathy, hepatorenal syndrome or variceal haemorrhage (portal hypertension).

Inclusion Criteria
Conditions indicative of decompensated liver disease including codes for ascites, hepatic encephalopathy, hepatorenal syndrome or variceal haemorrhage (portal hypertension).

Exclusion Criteria for Codes
Fetal cirrhosis
Early cirrhosis too advanced
Jaundice omitted as seems too non-specific

Borderline Cases to Highlight:
Codes describing acute hepatic injury - for example side effect of medication. May not capture the advanced nature of liver disease that looking to identify.

Codelist link: https://www.opencodelists.org/codelist/user/speed-vm/condition-advanced-decompensated-cirrhosis-of-the-liver/5c4c47b4/#search-results

**Comment by richiecroker** [comment]
@speed-vm can we discuss at CI team meeting on Monday please

**Comment by speed-vm** [comment]
Hi @richiecroker 

Metadata and title of codelist updated as per team discussion this morning. Discussion was around the broad nature of the codelist, and team felt better to make that clear in the description and title

Updated codelist:
https://www.opencodelists.org/codelist/user/speed-vm/condition-advanced-decompensated-cirrhosis-of-the-liver/1aba2c18/

**Comment by speed-vm** [comment]
Whilst looking at existing work for identification of end stage liver disease. Have found a paper [describing a validation study of ICD-9 codes to identify end stage liver disease](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4267226/pdf/nihms646806.pdf)

In this paper, they suggest that we should identify those with cirrhosis _and a_ decompensation event (eg varices). As a compromise and to be inclusive, I have generated two codelists (1x SNOMED and 1 x ICD-10) indicating cirrhosis _or a_ decompensation event. 

ICD-10 codes
https://www.opencodelists.org/codelist/user/speed-vm/condition-advanced-decompensated-liver-disease-and-associated-conditions-icd-10/523e926e/#tree

SNOMED
https://www.opencodelists.org/codelist/user/speed-vm/condition-advanced-decompensated-cirrhosis-of-the-liver/071038cf/

**Comment by richiecroker** [comment]
@speed-vm happy with both ICD-10 and SNOMED codelists

**Comment by speed-vm** [comment]
@lshbz1 these codelists have now been published.

**Comment by lshbz1** [comment]
Many thanks Vicky and Richard!
