### ISSUE TITLE
* PROCEDURE * ascitic drainage

### ISSUE THREAD

**Issue by lshbz1** [opensafely/codelist-development#227]
We will create a codelist for ascitic drainage. Regular ascitic drainage is a contraindication of Paxlovid for non-hospitalised COVID-19 patients.

**Comment by speed-vm** [comment]
@richiecroker are you happy with this one? If so, I will go ahead and publish.

**Comment by speed-vm** [comment]
Confirmed with Rich ok to go ahead 01/08/2022. Now published.
