### ISSUE TITLE
*MEDICINE* - Levothyroxine oral

### ISSUE THREAD

**Issue by a-d-brown** [opensafely/codelist-development#228]
### User Requirements
This codelist aims to identify instances of levothyroxine being prescribed orally. Patients receiving this medication will routinely have TFT's checked annually; the user intends to check whether TFT's have been monitored annually for patients which have been issued with oral levothyroxine.

### Search Terms
- Levothyroxine

### Borderline Case Discussion
None identified.

### Codelist: https://www.opencodelists.org/codelist/user/Andrew/levothyroxine/12a1ec36/

**Comment by a-d-brown** [comment]
@richiecroker if you could take a quick look over this when you get a chance that would be great - thanks.

**Comment by richiecroker** [comment]
@a-d-brown happy with codelist

**Comment by a-d-brown** [comment]
dm+d version published: https://www.opencodelists.org/codelist/opensafely/levothyroxine/33c99f4d/

**Comment by speed-vm** [comment]
@a-d-brown Happy with this update to levothyroxine codelist.

**Comment by a-d-brown** [comment]
Thanks, published new version.
