### ISSUE TITLE
Add category mappings to the ethnicity SNOMED codelist

### ISSUE THREAD

**Issue by alexwalkerepi** [opensafely/codelist-development#229]
[This codelist](https://www.opencodelists.org/codelist/opensafely/ethnicity-snomed-0removed) has numeric categories, but the associated categorisation is not easy to find. As it's been categorised according to 2001 census I think the labels should be in line with [this nomenclature](https://www.datadictionary.nhs.uk/data_elements/ethnic_category.html?hl=ethnicity).

6 categories, labels I think are:
```
1 - White
2 - Mixed
3 - Asian or Asian British
4 - Black or Black British
5 - Other Ethnic Groups
6 - Not stated
```
16 categories, labels I think are:
```
1 - White - British
2 - White - Irish
3 - White - Any other White background
4 - Mixed - White and Black Caribbean
5 - Mixed - White and Black African
6 - Mixed - White and Asian
7 - Mixed - Any other mixed background
8 - Asian or Asian British - Indian
9 - Asian or Asian British - Pakistani
10 - Asian or Asian British - Bangladeshi
11 - Asian or Asian British - Any other Asian background
12 - Black or Black British - Caribbean
13 - Black or Black British - African
14 - Black or Black British - Any other Black background
15 - Other Ethnic Groups - Chinese
16 - Other Ethnic Groups - Any other ethnic group
17 - Not stated
```
@andrewscolm could you check that the numbers match up with the labels? Especially for the 16 category.

**Comment by andrewscolm** [comment]
For the 6 categories:  category 5 could be 'Chinese or other ethnic group' as with the [census groups](https://www.ethnicity-facts-figures.service.gov.uk/style-guide/ethnic-groups#2001-census). There is no codes listed as category 6 (but perhaps it's good to keep it as a group to make it clear why it is known as 6 group?)

The 16 categories are correct. 

Should I add the labels to the metadata or add them as columns in the codelist? (e.g. [primis](https://www.opencodelists.org/codelist/primis-covid19-vacc-uptake/eth2001/v1/#full-list)) I think this is possible but I will need to double check.

**Comment by alexwalkerepi** [comment]
Great, thanks. I've edited the formatting for clarity.
