### ISSUE TITLE
*CONDITION* Atrial fibrillation or flutter

### ISSUE THREAD

**Issue by hmcd** [opensafely/codelist-development#23]
DEFINITION: Codes for a history of atrial fibrillation

Variables:
1) a binary variable denoting the presence of one of the codes at any point in the patient record. 
2) the earliest date of such a code.

CODE LISTS: 
Plan to 
1) check SNOMED
2) add to codelist in Read V2 
[AF_readv2.xlsx](https://github.com/opensafely/codelist-development/files/4865127/AF_readv2.xlsx)
3) map to CTV3
4) And add to QOF (CTV3) lists available 
[Atrial_fibrillation_diagnosis_codes_QOF.txt](https://github.com/opensafely/codelist-development/files/4864912/Atrial_fibrillation_diagnosis_codes_QOF.txt)
[Atrial_fibrillation_exception_reporting_codes.txt](https://github.com/opensafely/codelist-development/files/4864913/Atrial_fibrillation_exception_reporting_codes.txt)
[Atrial_fibrillation_review_codes.txt](https://github.com/opensafely/codelist-development/files/4864914/Atrial_fibrillation_review_codes.txt)

FLEXIBILITY NEEDED BETWEEN STUDIES: None. Other studies might want to consider medication status as separate variable.

EFFECTS ON COHORT SELECTION:  Consider requirement for patients to have been registered for at least 12 months before the index date, in order to allow for recording of relevant codes.

POTENTIAL BIASES: Ascertainment may depend on health-seeking behaviour, or be prompted by investigation of other cardiac disease.

**Comment by amirmehrkar** [comment]
@hmcd @brianmackenna @inglesp I've looked through this. Also discussed with @brianmackenna. 

Given that AF codes are pretty well established in primary care, I think the best option is to use TPP CTV3 QOF codelist (and ask TPP to obviously then generate the link to SNOMED)

There is already another issue that links to the aftershocks works. https://docs.google.com/spreadsheets/d/1m_aLIl6Nm4jqynYrqKgo_eeGDQf5wYV0uSCebotOMrI/edit?usp=sharing

So I would suggest:
1. include cluster AFIB
2. include cluster AFIBDI
3. include cluster AFIEXC
4. include cluster AFIBINVITE
5. include cluster AFIBPCADEC
6. include cluster AFIBPCAPU
7. **DO NOT** include AFIBRES

So perhaps this should be closed and merged with https://github.com/opensafely/anticoagulants-research/issues/1 although looking at the current https://codelists.opensafely.org/codelist/opensafely/atrial-fibrillation/#full-list codelist on opencodelists, the monitoring codes and exception codes are not included.

**Comment by hmcd** [comment]
That sounds good to me! @StatsFizz also suggested could use the AF component of the e-frailty index, but QOF might be a better choice.

**Comment by johntaz** [comment]
Thanks everyone - @amirmehrkar I've generated a codelist including your suggestions above. If approved I will submit to codelists openSAFELY.

@hmcd @StatsFizz 
[AF_QOF.xlsx](https://github.com/opensafely/codelist-development/files/4988032/AF_QOF.xlsx)

**Comment by hmcd** [comment]
Thanks @johntaz !

@amirmehrkar these all look appropriate if we're defining atrial fibrilliation OR atrial flutter - which seems appropriate given we're interested in risk factors for clots. In which case, shall we change the topic name to "Atrial fibrillation or flutter"?

**Comment by hmcd** [comment]
DEFINITION: Codes for a history of atrial fibrillation or atrial flutter

Variables:
(1) a binary variable denoting the presence of one of the codes at any point in the patient record.
(2) the earliest date of such a code.

CODE LISTS:
From Quality Outcomes Framework lists:
include cluster AFIB
include cluster AFIBDI
include cluster AFIEXC
include cluster AFIBINVITE
include cluster AFIBPCADEC
include cluster AFIBPCAPU
DO NOT include AFIBRES

FLEXIBILITY NEEDED BETWEEN STUDIES: None. Other studies might want to consider medication status as a separate variable.

EFFECTS ON COHORT SELECTION: Consider requirement for patients to have been registered for a period before the index date, in order to allow for recording of relevant codes.

POTENTIAL BIASES: Ascertainment may depend on health-seeking behaviour, or be prompted by investigation of other cardiac disease.
