### ISSUE TITLE
Remove incorrect labels column from Primis ethnicity codelist

### ISSUE THREAD

**Issue by alexwalkerepi** [opensafely/codelist-development#231]
[This codelist](https://www.opencodelists.org/codelist/primis-covid19-vacc-uptake/eth2001/v1/#full-list) has a column called `grouping_6_label`, which has categories that don't match the groupings. Particularly notable is 3- South Asian, which is incorrect, as that category has codes including e.g. Japanese, Malaysian etc.

I'd suggest removing the column entirely and instead adding the mapping to the About page, as per #229.

**Comment by andrewscolm** [comment]
@inglesp is it possible to amend the [primis codelist?](https://www.opencodelists.org/codelist/primis-covid19-vacc-uptake/eth2001/v1/#full-list)

**Comment by alexwalkerepi** [comment]
@inglesp apologies, I didn't communicate that we should keep the `grouping_6_id`, but just remove the `grouping_6_label` column, rather than both. It's the label that I think is incorrect, rather than the numeric columns.

**Comment by andrewscolm** [comment]
Yes, I think it would be best to keep `code`, `term`, `grouping_6_id` and `grouping_16_id`. Sorry again for not making this clear.

**Comment by inglesp** [comment]
Oh, sorry.  If we're keeping the IDs, shouldn't we also keep the (corrected!) labels?

**Comment by alexwalkerepi** [comment]
We could. Practice with other codelists has been to extract the numeric list and then label them later, though this is more because of established patterns from early days, rather well thought out strategy. For others we've now added mappings to metadata to make that easier e.g. [here](https://www.opencodelists.org/codelist/opensafely/ethnicity-snomed-0removed/2e641f61/#full-list). (the same mappings could be used here as they're both based on 2001 census categories)

One thought is that it might be advantageous for things to break for anybody who was unknowingly using the incorrect label column.

**Comment by inglesp** [comment]
OK, try now!

**Comment by andrewscolm** [comment]
Wonderful! Thanks Peter

**Comment by alexwalkerepi** [comment]
Great, thanks!
