### ISSUE TITLE
*DISEASE* Peripheral artery disease

### ISSUE THREAD

**Issue by hmcd** [opensafely/codelist-development#24]
DEFINITION: Codes for a diagnosis of peripheral artery disease

Variables:
1) a binary variable denoting the presence of one of the codes at any point in the patient record.
2) the earliest date of such a code.

CODE LISTS:
Plan to
1) check SNOMED
2) add to codelist in Read V2 [PVD_PAD_readv2.xlsx](https://github.com/opensafely/codelist-development/files/4868979/PVD_PAD_readv2.xlsx) which is a composite of peripheral arterial disease codelist by Angel Wong and Laurie Tomlinson, and a peripheral vascular disease codelist by Helen Strongman
3) combine with CALIBER primary care Peripheral Arterial Disease list by Julie George, Emily Herrett, Liam Smeeth, Harry Hemingway, Anoop Shah, Spiros Denaxas https://caliberresearch.org/portal/phenotypes/peripheralarterialdisease
4) map to CTV3
5) And add to QOF (CTV3) lists available
6) Review and refine as needed

FLEXIBILITY NEEDED BETWEEN STUDIES: None. 

EFFECTS ON COHORT SELECTION: Consider requirement for patients to have been registered for at least 12 months before the index date, in order to allow for recording of relevant codes.

POTENTIAL BIASES: Ascertainment may differ pre- and post- introduction to Quality Outcomes Framework in 2012/13.

Decisions to discuss: I have suggested limiting to peripheral arterial disease, so that disease reflects a common aetiology and expect common relationship between disease and COVID-19 death. If agree with that approach, will need to consider what to do with 'peripheral vascular disease' codes.

**Comment by amirmehrkar** [comment]
Hi @hmcd - I agree with the number 1 in your excel.

Also, the CALIBER codes makes sense - although I would say that I suspect there is quite a lot of variation in the coding of many of these Caliber codes in primary care systems. It would be interesting to see how many extra patients this presents with who DO not have another typical PAD code (from your excel or QOF).

The QOF codes [(PAD and PADEXC)  cluster IDs ](https://docs.google.com/spreadsheets/d/1m_aLIl6Nm4jqynYrqKgo_eeGDQf5wYV0uSCebotOMrI/edit#gid=565006268) are quite thin comparatively; probably reflecting the difficulty and historically less accurate coding of peripheral artery disease in primary care.

**Comment by hmcd** [comment]
Thanks @amirmehrkar , sorry for the slow response from me. 

Having gone through the codes in a bit more detail, I think that my original suggestion of trying to keep strictly to peripheral arterial disease won't work - a lot of the common codes are for 'peripheral vascular disease', and if we didn't include those we'd miss a lot of peripheral arterial disease and be selecting based on coding practice. 

The CALIBER codes take a fairly broad approach - they don't include anything that is definitely venous disease, but they do include 'peripheral vascular disease'. Similarly they include any codes for peripheral gangrene without specified aetiology, which assumes that e.g. infected surgical wounds or acral gangrene due to sepsis would be coded as such - or that misclassification from these would be minimal, which seems reasonable and better than omitting diabetic foot. 

The CALIBER codelists have been used in quite a few studies, and they've been found to behave prognostically as expected for PAD. https://caliberresearch.org/portal/phenotypes/peripheralarterialdisease 

So I'd suggest we use the CALIBER codelist, for diagnoses and procedures, and update with Helen Strongman/Angel Wong's more recent search.

In this version of a Read v2 list, I started with the CALIBER list of diagnoses and procedures for PAD and:

(1) removed the DVTs, thrombectomies and embolectomies from the CALIBER list, since we're looking at DVT and PE in a separate list. This removed:

DVTs:
G74y000 | Embolism and/or thrombosis of the common   iliac artery
G74y100 | Embolism and/or thrombosis of the internal iliac artery
G74y200 | Embolism and/or thrombosis of the external iliac artery
G74y300 | Embolism and thrombosis of the iliac artery unspecified
G742400 | Embolism and thrombosis of the femoral   artery
G742500 | Embolism and thrombosis of the popliteal artery
G742600 | Embolism and thrombosis of the anterior tibial artery
G742700 | Embolism and thrombosis of the dorsalis pedis artery
G742900 | Embolism and thrombosis of a leg artery NOS

Embolectomies/thrombectomies:
7A19200 | Open embolectomy of bifurcation of aorta
7A43100 | Open embolectomy of iliac artery
7A43111 | Open embolectomy of common iliac artery
7A44100 | Percutaneous transluminal embolectomy of iliac artery
7A4A200 | Open embolectomy of femoral artery
7A4A211 | Open thrombectomy of femoral artery
7A4A212 | Open femoral embolectomy
7A4A300 | Open embolectomy popliteal artery
7A4A311 | Open thrombectomy of popliteal artery
7A4B200 | Percutaneous transluminal embolectomy of femoral artery
7A4B300 | Percutaneous transluminal embolectomy of popliteal artery

(2) added in the codes from Helen Strongman/Angel Wong's more recent list that were consistent with the CALIBER list. I didn't add 'PAD monitoring' codes, as I'd be concerned that patients with diabetes might be monitored for PAD without having it. These codes are flagged as 'update', and this added:

16I..00 | Claudication distance
1M11000 | Ischaemic foot pain at rest
1M11100 | Ischaemic foot pain when walking
G734.00 | Peripheral arterial disease
G73z012 | Vascular claudication
G76A.00 | arterial insufficiency
C10FF11 | Type II diabetes mellitus with peripheral angiopathy
14NB.00 | H/O: Peripheral vascular disease procedure
7A56600 | percutaneous transluminal placement peripheral stent artery
14NB.00 | H/O: Peripheral vascular disease procedure
7A56600 | percutaneous transluminal placement peripheral stent artery

(3) done a quick but not exhaustive search of SNOMED for the key terms, to pick up any major gaps in the mapping between Read v2 and CTV3. I searched for peripheral arterial disease, intermittent claudication, and peripheral gangrene concepts. I didn't search for procedures in SNOMED.

The SNOMED code 399957001 "Peripheral arterial occlusive disease (disorder)" includes as a child 724441006 "Non-atherosclerotic chronic arterial occlusive disease (disorder)" so ideally we'd exclude that child code for mapping, but otherwise might need to review what comes up from the SNOMED mapping.

Here's my suggestion for mapping to CTV3
Read v2 
[Updated_CALIBER_Readv2_PAD.xlsx](https://github.com/opensafely/codelist-development/files/4994383/Updated_CALIBER_Readv2_PAD.xlsx)

SNOMED 
[SNOMED_PAD.xlsx](https://github.com/opensafely/codelist-development/files/4994384/SNOMED_PAD.xlsx)

What do you think?

**Comment by johntaz** [comment]
@amirmehrkar @hmcd @evansd 
Thanks for all your work on this @hmcd ! 
Can I forward these to Chris now (since I know he is on holiday from next week) and I'll repost the mapped CTV3 codes for review?

**Comment by hmcd** [comment]
Hi @johntaz sorry it took me so long. As I've taken quite a comprehensive approach, it seems more likely that others will suggest removing codes than adding them. So if Chris will be away next week it seems sensible to me to map it to CTV3 first, then we can review the mapped codes.

**Comment by hmcd** [comment]
HI @johntaz - just to say if the codelist has been mapped to CTV3, I'm available to review it today or tomorrow!

**Comment by StatsFizz** [comment]
Unfortunately, Chris is on holiday so we have to wait til he’s back for the codes to be mapped. I believe that’s not next week but the next. So if you could review asap when he’s back that would be fab. Thanks so much!

**Comment by johntaz** [comment]
@amirmehrkar @hmcd 

Chris has returned this codelist, please could you review? 

[CTV3_Raw_PAD.xlsx](https://github.com/opensafely/codelist-development/files/5102163/CTV3_Raw_PAD.xlsx)

**Comment by hmcd** [comment]
Hello, sorry I am struggling with this one! Needing to think about what we are trying to capture and why, and also what definitions might make sense for members of the public/GPs for the risk prediction tool. 

We originally wanted this to capture people with atherosclerotic arteries who didn't have a diagnosis of cardiovascular or cerebrovascular disease. But it's very hard from the codes to separate arterial from venous disease (and we wouldn't be interested in the very common pathology of varicose veins) as there's a lot of vague 'peripheral vascular disease' coding. There are also questions of whether we include aortic aneuryms/ aneurysmal disease more widely (often atherosclerotic component but can have other causes), surgery often/mostly done for reasons of atherosclerosis (likely to include some trauma patients) and foot ulcers without specified aetiology.

SO many of the codes are not limited to the patient group of interest that I worry we're likely to end up with a large patient group, only a subset of whom have atherosclerotic arteries.... and that's not really very useful. One option would be to have a narrow definition e.g. claudication, but we can't be confident that that would be coded and it'd not capture the more severe end in which patients can't walk to experience claudication... Happy to keep ploughing on at it, but I wonder whether this might be more trouble than it is worth given than it was marginal to the risk prediction tool? @StatsFizz @johntaz @amirmehrkar

**Comment by hmcd** [comment]
Discussed with @amirmehrkar @laurietomlinson and @johntaz yesterday 08/09/2020

Rationale for including this category in the risk group is that patients with peripheral arterial disease who have a COVID-19 infection may be at higher risk of MI/stroke than patients without peripheral arterial disease who have a COVID-19 infection.

This would be based on the assumption that diagnosed peripheral arterial disease would imply likely atherosclerosis of cerebral and/or cardiac arteries, which could be subclinical/undiagnosed, rather than that peripheral arterial disease itself would be a strong risk factor for MI/stroke. We discussed that this is an indirect rationale, and that peripheral arterial disease may not be a major risk factor for COVID-19 mortality - however, cardiovascular disease appears likely to be a very strong risk factor for COVID-19 mortality, and so we agreed that it would be desirable to include an indicator of peripheral arterial disease.

For the risk prediction tool, we need to define a set of patients using codelists that will correspond to a question that can be answered by self-report.

Much of the coding is 'peripheral vascular disease', for which it is unclear whether the disease is arterial or venous or both. Patients won't know how their disease is coded - they will know what symptoms they have and (largely) what disease they have.
If we include all of 'peripheral vascular disease' we should include peripheral venous disease in the codelist and the risk prediction tool question. However, this will combine venous and arterial disease, which would be expected to have different relationships with COVID-19 mortality. Individuals with varicose veins form a large population who are unlikely to be at similarly increased risk of COVID-19 mortality to individuals with peripheral arterial disease. We agreed we were not aiming to include 'peripheral vascular disease' as an umbrella group for venous and arterial disease.

Foot ulcers and gangrene have similar issues, and the decision not to include 'frailty' has been considered elsewhere.

We agreed to try to identify a group who specifically had peripheral arterial rather than venous disease. We agreed not to use the diagnosis codes for 'peripheral arterial disease' as this will select a subset of patients based on coding, excluding those coded as 'peripheral vascular disease', and we could not predict the effect of this.

Claudication was discussed as an option as typically caused by peripheral arterial disease but decided against as:
- as it records a symptom, may not be coded for those with a relevant diagnosis code
- patients with a code for 'claudication' as a symptom rather than a diagnosis may not be representative of all patients with claudication
- selects a group with middling severity of disease (ie severe enough to experience claudication, but not immobile/using a wheelchair/amputees)

Arterial surgery was discussed and we agreed this could be a suitable variable:
- individuals will know if they have had surgery to the arteries outside their heart and head
- the vast majority of these procedures will be due to peripheral arterial disease 
- agreed to include codes for surgery on peripheral arteries - including endarterectomies, bypassess, stents, but also 'repair' and 'reconstruction' of peripheral arteries on the basis that although these will include some individuals having surgery for other causes (such as trauma) we would expect the majority to reflect peripheral arterial disease, and this will also correspond to a straight forward question for the risk prediction tool.
- this group will include some individuals with PAD that is non-atherosclerotic (eg. aneuryms due to connective tissue disorders), likely to be a small minority, and may also be at increased risk of MI/stroke following COVID-19

This is the CTV3 mapping with my annotations prior to the discussion 
[CTV3_Raw_PAD_HMcomments.xlsx](https://github.com/opensafely/codelist-development/files/5197851/CTV3_Raw_PAD_HMcomments.xlsx)

Following the discussion, we are deciding to include categories 
7 endarterectomy, bypass or stent
8 artery repair/reconstruction/unspecified procedure
9 Percutaneous transluminal embolisation of femoral artery

We also agreed we should include amputations in this list - will need a new codelist for this.

SO the corresponding questions for the risk prediction tool would be:
"Have you ever had an amputation of a limb (or part of it)"
"Have you ever had surgery to your arteries, other than your head and heart (e.g. surgery to the arteries in your legs)?" (might need a definition of an artery)
Individuals answering yes would then be combined in one group for the model.

**Comment by hmcd** [comment]
DEFINITION: Surgery for peripheral artery disease

Variables:
(1) a binary variable denoting the presence of one of the codes at any point in the patient record.
(2) the earliest date of such a code.

CODE LISTS:

Process:
- Read v2
Started with CALIBER primary care Peripheral Arterial Disease list by Julie George, Emily Herrett, Liam Smeeth, Harry Hemingway, Anoop Shah, Spiros Denaxas https://caliberresearch.org/portal/phenotypes/peripheralarterialdisease
Removed DVTs, thrombectomies and embolectomies
Updated with consistent codes from Combined Read v2 codelists:
Read V2 PVD_PAD_readv2.xlsx which is a composite of peripheral arterial disease codelist by Angel Wong and Laurie Tomlinson, and a peripheral vascular disease codelist by Helen Strongman
- SNOMED supplementary search
Searched SNOMED for peripheral arterial disease, intermittent claudication, and peripheral gangrene concepts. 
Didn't search for procedures in SNOMED. 
Aim was to identify any major gaps in the Read v2 list.
- Mapped to CTV3
- Reviewed and discussed as above - agreed to limit to surgery on peripheral arteries, and that should also add a codelist for amputation and combine these groups

FLEXIBILITY NEEDED BETWEEN STUDIES: None.

EFFECTS ON COHORT SELECTION: If using to define an outcome, consider allowing for a period of registration (e.g. 12 months) to distinguish historical from incident events.

POTENTIAL BIASES: Ascertainment may differ pre- and post- introduction to Quality Outcomes Framework in 2012/13.
Will include some individuals with non-atherosclerotic peripheral arterial disease, and some individuals undergoing arterial surgery for other reasons such as trauma.

[CTV3_PAD_procedures.xlsx](https://github.com/opensafely/codelist-development/files/5197913/CTV3_PAD_procedures.xlsx)

**Comment by hmcd** [comment]
@johntaz @amirmehrkar @laurietomlinson 
I hope that essay captures our discussion reasonably! If it needs editing, please do say.

@johntaz Ben seemed to suggest there were clinicians with capacity to take on codelists - I'll struggle to get it done before going on leave next week, so if there's someone else who is happy to do it that would be amazing.

**Comment by amirmehrkar** [comment]
Hi @hmcd @johntaz @laurietomlinson 

Still finding this challenging. Thanks for your detailed write up which I agree with. 

Some addition thoughts:

1. If we are taking "atherosclerotic" peripheral artery disease to be a risk factor for atherosclerotic disease in the coronary/cerebral arteries, should we also include endarterectomies, bypassess, stents, but also 'repair' and 'reconstruction' of all arteries - the codelist doesnt seem to include arteries e.g. brachial (https://doi.org/10.1016/S0735-1097(96)00474-3) or subclavian artery (https://doi.org/10.1016/j.ijscr.2015.12.011). 

I believe there are CTV3 codes that reflect such proceedures of these arteries. Or is the idea to only use what are typically considered the most commonly affected arteries e.g. iliac, aorta, femorals (ie from Aorta and below)?

2. I made only a minor edit to the above explanation by providing a possible set of words (which we can evolve/tweak) to help patients distinguish an arterial procedure vs a venous procedure. 

3. I believe John is seeking some help on the amputation codes.

**Comment by hmcd** [comment]
Thanks @amirmehrkar ! I was happy to follow the CALIBER decision to go for aorta and lower limb arteries - it covers a coherent group that will be most of the patients we are interested in, and avoids confusion with e.g. arteriovenous fistulas or cerebral aneuryms. So perhaps we could just add to any explanatory notes for the question that this refers to surgery to the aorta or lower limbs?
