### ISSUE TITLE
*PROCEDURE* - Medication review

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#245]
### User Requirements
This codelist aims to identify patients who have had a general review of their medications.

### Existing codelists
https://www.opencodelists.org/codelist/opensafely/care-planning-medication-review-simple-reference-set-nhs-digital/61b13c39/
Not used as refset now inactive. Includes many condition/medication class specific reviews. Missing some key medication review codes e.g. Medication review done (314530002) which has 12m uses of SNOMED CT code in 20/21

https://www.opencodelists.org/codelist/nhsd-primary-care-domain-refsets/medrvw_cod/20200812/
Missing medication review codes e.g. Medication review of medical notes (93311000000106) which has 2.5m uses of SNOMED CT code in 20/21

### Search Terms
Medication review

### Inclusion Criteria for Codes
Codes indicating a review of medications.

### Exclusion Criteria for Codes
Condition/medication class specific reviews e.g. Anticoagulant medication review / Cardiac medication review - as these may indicate a review of only a subset of the patients medications.

### Borderline Cases to Highlight

Medication review of medical notes (93311000000106) - included as meets criteria, note not in NHSD refset - 2.5m uses of SNOMED CT code in 20/21
Comprehensive medication therapy review (428911000124108) - excluded - no use of SNOMED CT code in 20/21
Targeted medication therapy review (6021000124103) - excluded - seems to be review of specific medication - no use of SNOMED CT code in 20/21
Other medication review (394992006/394062004/704981000000100/393111006)  - excluded - non-specific review - inactive codes.

### Codelist: 
https://www.opencodelists.org/codelist/user/chriswood/medication-review/250a4bb0/

**Comment by speed-vm** [comment]
@chrisjwood16 Thank you - In addition to existing codelist - suggest to add in: 
Concordance and compliance level 2 medication review (procedure) (712761000000103) **35,550 usage 20/21**
Dispensing review of use of medications (Procedure) (279681000000105) **633,170 usage 20/21**
and to consider Medicines reconciliation (526421000000109) **326,770 usage 20/21**

Then I think it is ready. Please let me know when done and then I will update on codelist in medication-review repo.

**Comment by chrisjwood16** [comment]
Thanks @speed-vm .
- Concordance and compliance level 2 medication review (procedure) (712761000000103) - this seems to be more about if they are taking medications rather than a clinical review of appropriateness of medications - seen MUR given as an example of this - would suggest exclude.
- Dispensing review of use of medications (Procedure) (279681000000105) - similar to above less of a clinical review more of a concordance review [see this](https://www.psuk.co.uk/documents/Resources/SOPS-Documents/Dispensary-Checks-and-Processes/PSUK---Protocol-for-the-DRUM.docx) - suggest exclude
- Medicines reconciliation (526421000000109) - I wouldn't say full medication review is carried out at the point of meds reconciliation. If reviewing meds I would also include a medication review code. Suggest exclude.

**Comment by speed-vm** [comment]
@chrisjwood16 Great sounds good. Ok then its good to go. I will just wait until finalised and then update on repo shortly
