### ISSUE TITLE
*MEDICATION* Erythromycin

### ISSUE THREAD

**Issue by speed-vm** [opensafely/codelist-development#251]
**User Requirements**

In response to shortages due to strep A outbreak, a codelist for all oral preparations for erythromycin (all salts) is required.

**Search Terms**

**Inclusion Criteria for Codes**

**Exclusion Criteria for Codes**

**Borderline Cases to Highlight**

**Codelist**

**Comment by speed-vm** [comment]
@a-d-brown Looks good to me, just needs metadata adding

**Comment by a-d-brown** [comment]
@speed-vm - all done, published here:
https://www.opencodelists.org/codelist/opensafely/erythromycin-oral/7d3b84dd/
