### ISSUE TITLE
*MEDICATION* Phenoxymethylpenicillin

### ISSUE THREAD

**Issue by speed-vm** [opensafely/codelist-development#253]
**User Requirements**

In response to shortages due to strep A outbreak, a codelist for all oral preparations of phenoxymethylpenicillin is required

**Search Terms**
Phenoxymethylpenicillin 
0501011P0

**Inclusion Criteria for Codes**
Oral preparation

**Exclusion Criteria for Codes**
Eye drops 
Parenteral preparations

**Borderline Cases to Highlight**
Tenkicin - not prescribed in last in last four years in England, therefore not included

**Codelist** https://www.opencodelists.org/codelist/user/speed-vm/medication-phenoxymethylpenicillin/10e57827/

**Comment by speed-vm** [comment]
@a-d-brown please can you review so I can publish to dm+d? Thank you

**Comment by a-d-brown** [comment]
Looks good to me @speed-vm !

**Comment by speed-vm** [comment]
Meta data updated to be consistent with oral amoxicillin. https://www.opencodelists.org/codelist/user/chriswood/amoxicillin-oral/2ca7ab52/
@a-d-brown think would be good to make all consistent with same style of metadata as Chris has done here making them more 'searchable' and not just specific for Strep A.
