### ISSUE TITLE
*CONDITION* Scarlet fever

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#255]
### User Requirements
Following an increase in cases of [Scarlet Fever and invasive Group A Strep in the UK](https://ukhsa.blog.gov.uk/2022/12/05/group-a-strep-what-you-need-to-know/) this codelist aims to identify patients who have had a diagnosis of Scarlet Fever (other codelists will be created to cover other presentations). This codelist will be used in conjunction with codelists for antibiotics recommended for treatment of Group A Strep.

### Existing codelists
Nil found

### Search Terms
- Scarlet fever
- Scarlatina

### Inclusion Criteria for Codes
Codes indicating:
- diagnosis of Scarlet Fever
- suspected diagnosis of Scarlet Fever
- notification of case of Scarlet Fever

### Exclusion Criteria for Codes
Codes indicating:
- exposure to Scarlet Fever
- history of Scarlet Fever
- conditions not related to Group A Streptococcus

### Borderline cases
Otitis media due to scarlet fever (1090001000119105) and Myocarditis due to scarlet fever (1089931000119105).
Decided to include as indicate also Scarlet Fever infection.
Zero uses of these codes in 20-21 [according to NHS Digital data](https://digital.nhs.uk/supplementary-information/2022/snomed-code-usage)

### Codelist:
https://www.opencodelists.org/codelist/user/chriswood/scarlet-fever/1ba70f02/

**Comment by speed-vm** [comment]
Looks good. Comments below:
- metadata needs updating (specifically exclusion criteria as features some med review bits)
- suggest to include brief reason not looking for Group A strep, and specifically looking for Scarlet Fever. I went back to double check that so could be helpful to say that explicitly (ignore if my ignorance!).

Otherwise looks good to go.

**Comment by chrisjwood16** [comment]
Great thanks. Have updated metadata and added that this is one of a few codelists that will cover potential presentations.
