### ISSUE TITLE
*CONDITION* Streptococcal sore throat

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#256]
### User Requirements
Following an increase in cases of [Scarlet Fever and invasive Group A Strep in the UK](https://ukhsa.blog.gov.uk/2022/12/05/group-a-strep-what-you-need-to-know/) this codelist aims to identify patients who have had a possible diagnosis of Streptococcal sore throat.

We have taken a pragmatic approach where by codes for sore throat/pharyngitis/tonsilitis have been included where an alternative cause for the sore throat is not stated (eg. Viral sore throat). This codelist will be used in conjunction with codelists for antibiotics recommended for treatment of Group A Strep.

### Existing codelists
Nil found

### Search Terms
- Sore throat
- Pharyngitis
- Tonsillitis

### Inclusion Criteria for Codes
Codes indicating:
- Streptococcal acute sore throat/pharyngitis/tonsillitis
- Bacterial acute sore throat/pharyngitis/tonsillitis
- Acute sore throat/pharyngitis/tonsillitis where no specific cause listed

### Exclusion Criteria for Codes
Codes indicating:
- sore throat/pharyngitis/tonsillitis where other cause specified e.g. viral pharyngitis
-  sore throat/pharyngitis/tonsillitis where non Group A Strep related - e.g. pneumococcal 
- chronic tonsillitis sore throat/pharyngitis/tonsillitis

### Borderline cases
NA

### Codelist:
https://www.opencodelists.org/codelist/user/chriswood/group-a-streptococcal-sore-throat/2924ced0/

**Comment by speed-vm** [comment]
This is a pragmatic codelist incorporating a number of codes for sore throat/pharyngitis/tonsillitis where Group A Strep may be the cause to improve sensitivity. 

Would you consider phrasing as - We have taken a pragmatic approach where by codes for sore throat/pharyngitis/tonsilitis have been included where an alternative cause for the sore throat is not provided - or something to that effect! struggling for phrasing.

TBC

**Comment by chrisjwood16** [comment]
As discussed

**Comment by speed-vm** [comment]
Yes, happy with above.
