### ISSUE TITLE
*CONDITION* Invasive Group A Strep

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#257]
### User Requirements
Following an increase in cases of [Scarlet Fever and invasive Group A Strep in the UK](https://ukhsa.blog.gov.uk/2022/12/05/group-a-strep-what-you-need-to-know/) this codelist aims to identify patients who have had a diagnosis of Invasive Group A Strep including sepsis, necrotizing fasciitis and streptococcal toxic shock syndrome caused by Group A Strep. This codelist will be used in conjunction with codelists for antibiotics recommended for treatment of Group A Strep.

### Existing codelists
Nil found

### Search Terms
- Group A Strep
- Group A beta-haemolytic strep
- Streptococcus Group A
- Streptococcus pyogenes

### Inclusion Criteria for Codes
Codes indicating:
- Invasive Group A Strep
- Suspected Invasive Group A Strep infection
- Necrotizing fasciitis caused by Group A Strep
- Sepsis caused by Group A Strep
- Pneumonia caused by Group A Strep
- Streptococcal toxic shock syndrome

### Exclusion Criteria for Codes
Codes indicating:
- Other Group A strep related infections
- Non-Group A strep infections
- Codes just listing Group A Strep / Streptococcus pyogenes without context (not clear if indicating isolation of organism or where from).
- Codes indicating skin infections- cellulitis, ecthyma, neonatal pyoderma

### Borderline cases
NA

### Codelist:
https://www.opencodelists.org/codelist/user/chriswood/invasive-group-a-strep/42344205/

**Comment by chrisjwood16** [comment]
Excluded codes just listing Group A Strep / Streptococcus pyogenes without context (not clear if indicating isolation of organism or where from). 
Excluded codes for skin infections (non-invasive) - cellulitis, ecthyma, neonatal pyoderma

Borderline cases - Bronchopneumonia caused by Group A Streptococcus (10625151000119107), Pneumonia caused by infection caused by Streptococcus pyogenes (441942006) - Zero uses of these codes in 20-21 [according to NHS Digital data](https://digital.nhs.uk/supplementary-information/2022/snomed-code-usage)

**Comment by speed-vm** [comment]
Looks ok, ready to publish.
