### ISSUE TITLE
*TEST* Throat swab

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#258]
### User Requirements
Following an increase in cases of [Scarlet Fever and invasive Group A Strep in the UK](https://ukhsa.blog.gov.uk/2022/12/05/group-a-strep-what-you-need-to-know/) this codelist aims to identify patients who have had a result from a throat swab. Within S1 it appears that the code "Ear nose and throat microscopy, culture and sensitivities (995591000000102)" may be used for results (although possibly varies by lab). Ear nose and throat are often all listed for a swab/result but could potentially be any of the 3 - this list will therefore not be specific for throat swabs but may provide useful information on trends of numbers of ENT swabs undertaken.

This codelist will be used in conjunction with codelists for antibiotics recommended for treatment of Group A Strep.

### Existing codelists
Nil found

### Search Terms
- Ear nose and throat microscopy, culture and sensitivities
- Oropharyngeal culture
- Throat culture
- Oropharyngeal swab
- Pharynx swab
- Throat swab
- Swab from pharynx

### Inclusion Criteria for Codes
Codes indicating:
Throat swab taken
Throat swab result
Ear/nose/throat swab taken (as combined code may be in use for throat swab).
Ear/nose/throat swab MC&S (as combined code may be in use for throat swab result).

### Exclusion Criteria for Codes
Codes indicating:
- Swabs specifying test for none GAS - e.g. chlamydia/gonorrhea
- Swabs taken from sites other than throat - e.g. nasopharynx
- Swabs taken from combination of sites likely not to be looking for GAS - e.g. swab of anterior nares and anus and throat

### Borderline cases
Codes where mentions "Ear, nose and throat" - included as "EN&T" can be used as a catchall for any of these.

### Codelist:
https://www.opencodelists.org/codelist/user/chriswood/throat-swab/4c388e4e/

**Comment by speed-vm** [comment]
@chrisjwood16 

Metadata - review first paragraph last sentence, it is repeated

Codelist had two extras for you to consider. Since your are considering ear nose and throat swabs it seems sensible to also include just nose and throat.

https://www.opencodelists.org/codelist/user/chriswood/throat-swab/5fe28197/diff/65480183/
Otherwise looks good to me.

**Comment by chrisjwood16** [comment]
Thanks Vicky,
I've updated User Requirements section above to remove repeated info.
Have included Swab from pharynx and Nose/throat culture for bacteria.
Have left out Combined nasopharyngeal and oropharyngeal swab as that seems to be a swab of 2 sites using same swab.
Are you happy with this version? 
https://www.opencodelists.org/codelist/user/chriswood/throat-swab/4c388e4e/

**Comment by speed-vm** [comment]
Yes happy @chrisjwood16 , thanks
