### ISSUE TITLE
*PROCEDURE* Sore throat clinical prediction rules (feverPAIN/Centor)

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#259]
### User Requirements
Following an increase in cases of [Scarlet Fever and invasive Group A Strep in the UK](https://ukhsa.blog.gov.uk/2022/12/05/group-a-strep-what-you-need-to-know/) this codelist aims to identify patients where the "feverPAIN" or "Centor" clinical prediction rules have been used.

NICE guidance on sore throat (acute) currently recommends two clinical prediction rules (CPR), feverPAIN and Centor, to guide clinical decision making around people most likely to benefit from an antibiotic.

This codelist will be used in conjunction with codelists for antibiotics recommended for treatment of Group A Strep.

### Existing codelists
Nil found

### Search Terms
- feverPAIN
- Centor

### Inclusion Criteria for Codes
Codes indicating:
Assessment using either feverPAIN or Centor score
Clinical score from either feverPAIN or Centor

### Exclusion Criteria for Codes
Codes indicating:
N/A

### Borderline cases
N/A

### Codelist:
https://www.opencodelists.org/codelist/user/chriswood/sore-throat-clinical-prediction-rules/5df67530/

**Comment by a-d-brown** [comment]
This all looks good to me @chrisjwood16 , can't see anything to amend.

**Comment by chrisjwood16** [comment]
Published here:
https://www.opencodelists.org/codelist/user/chriswood/sore-throat-clinical-prediction-rules/5df67530/
