### ISSUE TITLE
*CLINICAL CONDITION* Kidney and other organ transplant recipient (solid organ)

### ISSUE THREAD

**Issue by StatsFizz** [opensafely/codelist-development#26]
DEFINITION: Patients who have a organ transplant code (i) for kidney, and (ii) for something else, ever on their records

CODE LISTS: 

Based on existing codelist for organ transplant, with the following changes:
(i) Laurie has marked a number of codes in the Nature paper codelist as not being organ transplant. Some are removal of transplant and some are not an organ. We want to remove them. 
(ii) Laurie also split into kidney, non-specific and heart/lung/pancreas/bowel

So what I want to do is create two new codelists which are largely subsets of the existing transplant codelists: (i) kidney  and (ii) other.  [I have two excel spreadsheets for the two proposed new codelists but don't know how to attach here]

FLEXIBILITY NEEDED BETWEEN STUDIES: None

EFFECTS ON COHORT SELECTION: Some records will only be held by hospitals but this is likely to be quite low.

POTENTIAL BIASES:

CLINICAL SIGN OFF & DATE:

EPIDEMIOLOGY SIGN OFF & DATE:

SHARED WITH WIDER TEAM: Yes/No

FINAL SIGN OFF DATE (and apply label)

**Comment by StatsFizz** [comment]
First file (kidney_transplant) includes all kidney transplant codes from solid organ list and 2 additional kidney transplant QOF codes from CKD list - put together by Laurie and Caroline M from the original CKD and transplant lists. 

Second file (other transplant) includes other codes from previous solid organ list but without codes Laurie thought were not to do with an organ. 

[kidney transplant_CMinEW.zip](https://github.com/opensafely/codelist-development/files/4898354/kidney.transplant_CMinEW.zip)
[organ transplant_not kidney_CMinEW.zip](https://github.com/opensafely/codelist-development/files/4898355/organ.transplant_not.kidney_CMinEW.zip)

**Comment by cminassian** [comment]
@StatsFizz, @laurietomlinson, @CarolineMorton, the 2 codelists Fizz attached are ready and I think just need signing off before I can upload them to codelists.opensafely.org.

**Comment by cminassian** [comment]
DEFINITION: Patients who ever had an organ transplant code for (i) kidney, and (ii) other organ (not kidney)

CODE LISTS: 

CTV3 Kidney transplant codelist:
[CTV3-kidney-transplant-14072020.xlsx](https://github.com/opensafely/codelist-development/files/4920565/CTV3-kidney-transplant-14072020.xlsx)

This codelist (kidney transplant) is derived from the Solid Organ Transplant codelist:
[opensafely-solid-organ-transplantation-2020-04-10_redoneLT.xlsx](https://github.com/opensafely/codelist-development/files/4920567/opensafely-solid-organ-transplantation-2020-04-10_redoneLT.xlsx)
and Chronic Kidney Disease codelist:
[opensafely-chronic-kidney-disease-2020-04-14_LTredone.xlsx](https://github.com/opensafely/codelist-development/files/4920569/opensafely-chronic-kidney-disease-2020-04-14_LTredone.xlsx)

Codes relating to kidney transplant were selected from the Solid Organ Transplant codelist following clinical review by Laurie. In addition, 2 QOF codes relating to kidney transplant (not included in the Solid Organ Transplant codelist) were selected from the Chronic Kidney Disease codelist.

CTV3 other organ transplant (not kidney) codelist:
[CTV3-organ-transplant-not-kidney-14072020.xlsx](https://github.com/opensafely/codelist-development/files/4920579/CTV3-organ-transplant-not-kidney-14072020.xlsx)

This codelist (other organ transplant) is a subset of the Solid Organ Transplant codelist. It excludes codes indicating a kidney transplant, and additional codes marked by Laurie indicating removal of transplant or non-organ transplant.

FLEXIBILITY NEEDED BETWEEN STUDIES: None

EFFECTS ON COHORT SELECTION: 

POTENTIAL BIASES:

CLINICAL SIGN OFF & DATE:

EPIDEMIOLOGY SIGN OFF & DATE:

SHARED WITH WIDER TEAM: Yes/No

FINAL SIGN OFF DATE (and apply label)
