### ISSUE TITLE
*MEDICATION* Co-amoxiclav (oral)

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#260]
**User Requirements**
In response to shortages due to strep A outbreak, a codelist for all oral preparations of co-amoxiclav is required.

[Group A streptococcus in children: Interim clinical guidance summary](https://www.england.nhs.uk/publication/group-a-streptococcus-communications-to-clinicians/) - [PDF updated 30th December 2022](https://www.england.nhs.uk/wp-content/uploads/2022/12/PRN00080-Interim-clinical-guidance-summary-Group-A-streptococcus-30122022.pdf) lists this as an option in the event of non-availability of other antibiotics.

**Search Terms**
co-amoxiclav

**Inclusion Criteria for Codes**
Any oral formulation of co-amoxiclav (amoxicillin + clavulanic acid in combination)

**Exclusion Criteria for Codes**
Non-oral formulations - (solution for injection)

**Borderline Cases to Highlight**

**Codelist** 
https://www.opencodelists.org/codelist/user/chriswood/co-amoxiclav-oral/4985ce58/

**Comment by speed-vm** [comment]
@chrisjwood16 looks good to me, ready to dm+d
