### ISSUE TITLE
*MEDICATION* Cefalexin (oral)

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#261]
**User Requirements**
In response to shortages due to strep A outbreak, a codelist for all oral preparations of cefalexin is required.

[Group A streptococcus in children: Interim clinical guidance summary](https://www.england.nhs.uk/publication/group-a-streptococcus-communications-to-clinicians/) - [PDF updated 30th December 2022](https://www.england.nhs.uk/wp-content/uploads/2022/12/PRN00080-Interim-clinical-guidance-summary-Group-A-streptococcus-30122022.pdf) lists this as an option in the event of non-availability of other antibiotics.

**Search Terms**
cefalexin
cephalexin

**Inclusion Criteria for Codes**
Any oral formulation of cefalexin

**Exclusion Criteria for Codes**
Non-oral formulations - (solution for injection)

**Borderline Cases to Highlight**

**Codelist** 
https://www.opencodelists.org/codelist/user/chriswood/cefalexin-oral/1a19a7e4/

**Comment by speed-vm** [comment]
@chrisjwood16 Looks good. Only thing is that you have said searched for cephalexin, but that is not listed as one of the searches. 
Otherwise ready to dm+d

**Comment by chrisjwood16** [comment]
Strange - I'm sure I did search it. I've updated here to include - no matches.
https://www.opencodelists.org/codelist/user/chriswood/cefalexin-oral/1a19a7e4/

**Comment by speed-vm** [comment]
Looks good now @chrisjwood16 , can see that search.

**Comment by chrisjwood16** [comment]
dm+d uploaded here - https://www.opencodelists.org/codelist/opensafely/cefalexin-oral/4eeb4e44/
