### ISSUE TITLE
*MEDICATION* Flucloxacillin (oral)

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#262]
**User Requirements**
In response to shortages due to strep A outbreak, a codelist for all oral preparations of flucloxacillin is required.

[Group A streptococcus in children: Interim clinical guidance summary](https://www.england.nhs.uk/publication/group-a-streptococcus-communications-to-clinicians/) - [PDF updated 30th December 2022](https://www.england.nhs.uk/wp-content/uploads/2022/12/PRN00080-Interim-clinical-guidance-summary-Group-A-streptococcus-30122022.pdf) lists this as an option in the event of non-availability of other antibiotics.

**Search Terms**
flucloxacillin 

**Inclusion Criteria for Codes**
Any oral formulation of flucloxacillin 

**Exclusion Criteria for Codes**
Non-oral formulations - (solution for injection)
Combination products - e.g. Co-fluampicil
MDR BNF code - DO NOT USE(0501012H0AAAGAG)

**Borderline Cases to Highlight**

**Codelist** 
https://www.opencodelists.org/codelist/user/chriswood/flucloxacillin-oral/30765b23/

**Comment by speed-vm** [comment]
@chrisjwood16 looks good to me to dm+d

**Comment by chrisjwood16** [comment]
dm+d uploaded here - https://www.opencodelists.org/codelist/opensafely/flucloxacillin-oral/35dbdb0f/
