### ISSUE TITLE
*Medicine* Paxlovid (Nirmatrelvir/ritonavir) absolute contraindicated medications

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#266]
**User Requirements**
In a study on effectiveness of Paxlovid, a codelist is required to exclude patients who are on specific drugs which would contraindicate use due to drug-drug interactions. A previous [codelist](https://www.opencodelists.org/codelist/opensafely/sps-paxlovid-interactions-do-not-use/58f87823/) was based upon the [Specialist Pharmacist Service interaction information](https://web.archive.org/web/20220208181734/https://www.sps.nhs.uk/wp-content/uploads/2022/01/Paxlovid-SPS-20220202.pdf) however this has now been replaced with guidance to refer to [SmPC](https://www.medicines.org.uk/emc/product/13145) and [University of Liverpool COVID-19 Drug Interaction checker](https://www.covid19-druginteractions.org/view_all_interactions). 

We known from correspondence with specialists within CMDUs and information given on the University of Liverpool COVID-19 Drug Interaction checker that where concomitant administration is contraindicated due to interactions, there are certain drugs which might be withheld for short periods (where there are unlikely to be significant clinical consequences) to allow Paxlovid treatment for example statins.

**Sensitivity vs specificity**
Aim is to only include drugs where the majority of the patients prescribed these drugs would be considered not suitable to receive Paxlovid. This would be where there is a likely interaction with negative clinical consequences and drug is not generally suitable to be withheld etc.

**Search Terms/Strategy**
1) Use interaction summary taken from [University of Liverpool COVID-19 Drug Interaction checker](https://www.covid19-druginteractions.org/view_all_interactions) - identify all drugs listed as "Do not coadminister".
2) Manual clinician one review (CW) to identify common themes/rational for management of interaction - e.g. "Long half-life", "Persisting inducing effect", "Withhold drug x whilst on treatment with Paxlovid"
3) Use string matching to flag different themes across summaries.
4) Clinician one (CW) check for accuracy of string matching.
5) Clinician one (CW) review of unmatched interaction to identify if absolute contraindicated (e.g. any strategies given such as withholding medication, is this a medication that is given continuously without break or only taken when required).
6) Clinician two(AB) review of unmatched interaction to identify if absolute contraindicated (e.g. any strategies given such as withholding medication, is this a medication that is given continuously without break or only taken when required).
7) Consensus agreement between clinician one and clinician two for any outstanding interactions.

https://docs.google.com/spreadsheets/d/16sn4X0RQimPvcjfO-ijCYBpPJ2hl3r2J1JAm5JHgHZk/edit?usp=sharing

**Inclusion Criteria for Codes**
Drugs with likely interaction with negative clinical consequences and drug is not generally suitable to be withheld/no other suggested mitigation strategy.
Drugs listed as do not co-administer with long half-lives or persisting inducer effects (withholding wouldn't mitigate interaction).

**Exclusion Criteria for Codes**
Drugs with likely interaction with negative clinical consequences but drug is suitable to be withheld/or other suggested mitigation strategy.
Drugs without likely interaction with negative clinical consequences

**Borderline Cases to Highlight**
Tacrolimus/Sirolimus/Everolimus/Ciclosporin - all listed as complex interactions to manage and needing frequent monitoring so not recommended but strategy is given for managing interaction - so excluded from this codelist.

**Codelist**
Pseudio-BNF = https://www.opencodelists.org/codelist/user/chriswood/paxlovid-nirmatrelvirritonavir-absolute-contraindications/1057c5ed/
dm+d = https://www.opencodelists.org/codelist/opensafely/paxlovid-nirmatrelvirritonavir-absolute-contraindications-dmd/774852b7/

**Comment by a-d-brown** [comment]
Codelist checked and approved.
