### ISSUE TITLE
*MEDICINE* Mixed (biphasic) insulin

### ISSUE THREAD

**Issue by a-d-brown** [opensafely/codelist-development#271]
**User Requirements**
Identify patients who are taking a bisphasic insulin, i.e. a long-acting component with a short or intermediate acting component. This will be used alongside a GLP-1 codelist to identify a specific cohort of patients and assess the impact of the impact of GLP-1's being prescribed for weight loss.

**Search Terms**
- Insulin

**Inclusion Criteria for Codes**
- Refers to a biphasic insulin with no other medicines in combination.

**Exclusion Criteria for Codes**
- Refers to a short-acting, intermediate acting, or long-acting insulin not in combination with another insulin type.
- Refers to a biphasic insulin in combination with a non-insulin medication.
- Refers to a non-insulin product.
- Bisphasic products discontinued in the UK.

**Borderline Cases to Highlight**
None

**Codelist**
https://www.opencodelists.org/codelist/user/Andrew/mixed-biphasic-insulin/32462c93/#tree

**Comment by chrisjwood16** [comment]
I'm happy to approve this codelist.

**Comment by a-d-brown** [comment]
Thanks, here is the dm+d version for completeness:
https://www.opencodelists.org/codelist/user/Andrew/mixed-biphasic-insulin-dmd/69ca92e9/#full-list
