### ISSUE TITLE
*MEDICINE* GLP-1's (excluding those combined with insulin)

### ISSUE THREAD

**Issue by a-d-brown** [opensafely/codelist-development#272]
**User Requirements**
Identify patients who are taking a GLP-1 mimetic (excluding products which are combined with insulin). This will be used to identify assess the impact of the impact of GLP-1s being prescribed for weight loss.

**Search Terms**
Antidiabetic drugs

**Inclusion Criteria for Codes**
- Refers to a GLP-1 mimetic without insulin in combination.

**Exclusion Criteria for Codes**
- Refers to a GLP-1 mimetic with insulin in combination.
- Refers to an antidiabetic drug which is not a GLP-1 mimetic.

**Borderline Cases to Highlight**
- Albiglutide - can be ignored as withdrawn from market, no longer available.
- Tirzepatide - this drug is an agonist of both GIP and GLP-1 receptors. I think it's probably still ok to class it with the pure GLP-1 agonists given that the overall effect of agonising either receptors is similar, i.e. to promote insulin secretion. Currently only 1 prescription in past 12m, but NICE are expected to [issue guidance](https://www.nice.org.uk/guidance/indevelopment/gid-ta10835) on its use in Oct23. Included in the codelist now to help futureproof it.

**Codelist**
https://www.opencodelists.org/codelist/user/Andrew/glp-1s-excluding-those-combined-insulin/34f8ec89/#tree

**Comment by chrisjwood16** [comment]
Happy to approve this.
Probably worth mentioning this list of GLP-1s includes those licensed only for weight loss (Saxenda).
Also worth setting a reminder to review regularly as Wegovy is due to launch at some point this year.

**Comment by a-d-brown** [comment]
Thanks, I'll make sure to point out the licencing in the metadata description.

Final dm+d codelist: https://www.opencodelists.org/codelist/user/Andrew/glp-1s-excluding-those-combined-insulin-dmd/1e9c394a/
