### ISSUE TITLE
*MEDICINE* GLP-1's combined with insulin

### ISSUE THREAD

**Issue by a-d-brown** [opensafely/codelist-development#273]
**User Requirements**
Identify patients who are taking a product which contains a GLP-1 mimetics in combination with insulin. This will be used to identify assess the impact of the impact of GLP-1s being prescribed for weight loss.

**Search Terms**
- Antidiabetic drugs
- Insulin

**Inclusion Criteria for Codes**
- Refers to a GLP-1 mimetic in combination with insulin.

**Exclusion Criteria for Codes**
- Refers to a GLP-1 mimetic without insulin in combination.
- Refers to an antidiabetic drug which is not a GLP-1 mimetic.

**Borderline Cases to Highlight**
None

**Codelist**
https://www.opencodelists.org/codelist/user/Andrew/glp-1s-in-combination-with-insulin/6717d2f3/#tree

**Comment by chrisjwood16** [comment]
Happy to approve this.

**Comment by a-d-brown** [comment]
Thanks!

Final dm+d codelist:
https://www.opencodelists.org/codelist/user/Andrew/glp-1s-in-combination-with-insulin-dmd/058cc615/
