### ISSUE TITLE
*MEDICATION* Dialysis

### ISSUE THREAD

**Issue by StatsFizz** [opensafely/codelist-development#28]
For the risk prediction models I want a dialysis codelist. This (below) is Laurie's selection from our previous CKD list, of those codes related to dialysis, plus three codes from the transplant list that related to removal of kidney transplants.

[dialysis_CMinEW.zip](https://github.com/opensafely/codelist-development/files/4898377/dialysis_CMinEW.zip)

**Comment by cminassian** [comment]
@StatsFizz, @CarolineMorton, @laurietomlinson this dialysis codelist is ready, just needs signing off before uploading.

**Comment by cminassian** [comment]
DEFINITION: Patients who ever had a dialysis record

CODE LISTS: 

CTV3 dialysis codelist: 
[CTV3-dialysis-14072020.xlsx](https://github.com/opensafely/codelist-development/files/4920496/CTV3-dialysis-14072020.xlsx)

This dialysis codelist is derived from the Chronic Kidney Disease codelist:
[opensafely-chronic-kidney-disease-2020-04-14_LTredone.xlsx](https://github.com/opensafely/codelist-development/files/4920504/opensafely-chronic-kidney-disease-2020-04-14_LTredone.xlsx)
and the Solid Organ Transplant codelist:
[opensafely-solid-organ-transplantation-2020-04-10_redoneLT.xlsx](https://github.com/opensafely/codelist-development/files/4920513/opensafely-solid-organ-transplantation-2020-04-10_redoneLT.xlsx)

Codes relating to dialysis were selected from the Chronic Kidney Disease codelist following clinical review by Laurie. In addition, 3 codes relating to removal of kidney transplant were selected from the Solid Organ Transplant codelist and included in this dialysis list.

FLEXIBILITY NEEDED BETWEEN STUDIES: None

EFFECTS ON COHORT SELECTION: 

POTENTIAL BIASES:

CLINICAL SIGN OFF & DATE:

EPIDEMIOLOGY SIGN OFF & DATE:

SHARED WITH WIDER TEAM: Yes/No

FINAL SIGN OFF DATE (and apply label)
