### ISSUE TITLE
*MEDICATION*: Antidepressants for pain

### ISSUE THREAD

**Issue by alschaffer** [opensafely/codelist-development#287]
### User requirements

This is to identify prescribing of antidepressants with an indication for pain to people waiting on procedure waiting lists. This population has high rates of pain, and thus it is useful to distinguish between antidepressants more likely to be prescribed for pain vs mental health symptoms. 

### Sensitivity versus specificity

Probably sensitive. Any antidepressant that is either listed in a relevant guidance for treatment of pain (e.g., neuropathic pain), or medicines that are likely to be used off-label to treat pain based on evidence or common practice. 

### Relevant definitions or links to important reference sources

Some antidepressants are indicated to treat neuropathic pain, most commonly TCAs or SNRIs. NICE guidance (https://www.nice.org.uk/guidance/cg173) recommends use of amitriptyline and duloxetine, and venlafaxine is not recommended outside of specialist settings. This meta-analysis of pharmacotherapy for neuropathic pain (https://www.thelancet.com/journals/laneur/article/PIIS1474-4422(14)70251-0/fulltext) includes TCAs (amitriptyline, nortriptyline, imipramine) and SNRIs (duloxetine, venlafaxine, desvenlafaxine).

### Coding system

dm+d

### Existing relevant codelists

TCAs: https://www.opencodelists.org/codelist/opensafely/tricyclic-and-related-antidepressants-dmd/1268eae1/

**Comment by alschaffer** [comment]
@speed-vm @chrisjwood16 I'd appreciate input on this. One option is to simply create categories for TCAs  and SNRIs, but I don't know if that is not specific enough.

**Comment by speed-vm** [comment]
There are three main drugs licensed to treat depression but that are also used for the treatment of neuropathic pain **amitriptyline, nortriptyline,** and **duloxetine**. Only amitriptyline is licensed for this neuropathic pain.

Venlafaxine is an antidepressant which can be used off license for neuropathic pain but must be initiated by specialist. 

**TCAs:** 
Amitriptyline - (Licensed for neuropathic pain since 2019) 
Nortriptyline - Listed as an alternative for neuropathic pain in case amitriptyline not tolerated.

**SNRIs:** 
Duloxetine recommended as a first line option for neuropathic pain by NICE. Not licensed for neuropathic pain) 
Venlafaxine - must be initiated by specialist. 

Based on NICE guidance and BNF, I think it would be best to include the three main agents as most likely to be used for this alternative indication. Use of others, including venlafaxine, more unusual and more likely to be for primary licensed indications.

**Comment by alschaffer** [comment]
@speed-vm Vicky that sounds good to me. Looking at OpenCodelists, for duloxetine there are formulations that fall under Chapter 7 (Obstetrics, Gynaecology and Urinary Tract Disorders). Presumably that is for urinary incontinence or similar and should not be included?  There is also an amitriptyline/ketamine cream (Chapter 10) which sounds like it would be for neuropathic pain.
![image](https://github.com/opensafely/codelist-development/assets/37759997/23f27790-942a-4b60-8a75-08b1b7cc7215)

**Comment by speed-vm** [comment]
Yes, exactly the same thoughts re uro/gynae, but I have excluded the topical as not prescribed recently in primary care and NICE recommendations are for oral preparations.

Here is codelist ready for review: 
https://www.opencodelists.org/codelist/user/speed-vm/antidepressants-for-pain/4886a4db/

**Comment by chrisjwood16** [comment]
@speed-vm I'm not so sure about the inclusion of nortriptyline here - it isn't listed in NICE guidance/CKS as a first line option and generally if amitriptyline isn't tolerated the guidance is to offer a different class.
![image](https://github.com/opensafely/codelist-development/assets/96439159/0f33285f-001f-4343-a557-fb4a4c884260)

**Comment by speed-vm** [comment]
Discussion between @chrisjwood16 and myself regarding nortriptyline. 
BNF recommends nortriptyline as an alternative to amitriptyline if not tolerated. 

Concluded that use is likely to be minimal, and prescribing is most likely to be for primary licensed indications. We have therefore opted to follow NICE guidelines and include only amitriptyline and duloxetine, as antidepressants used for pain management. 

New codelist below for @chrisjwood16 sign off
https://www.opencodelists.org/codelist/user/speed-vm/antidepressants-for-pain/12ee4aec/

**Comment by chrisjwood16** [comment]
@speed-vm happy to approve this

**Comment by speed-vm** [comment]
@alschaffer @chrisjwood16 thank you, this has now been converted to dm+d and published.
https://www.opencodelists.org/codelist/user/speed-vm/antidepressants-for-pain-dmd/60cf6481/

**Comment by alschaffer** [comment]
@speed-vm Given the low rates of amitriptyline prescribing in the data, I was looking at the codelist and noticed that it doesn't include the following amitriptyline VMPs, is this correct?


![Image](https://github.com/opensafely/codelist-development/assets/37759997/ea54da85-f768-4359-b841-811ce1a0602b)

**Comment by alschaffer** [comment]
@speed-vm Are the missing related to the BNF mapping having been updated recently? Might be worth updating the dmd codelist (I can't since it's your codelist).

**Comment by speed-vm** [comment]
Hi @alschaffer , 
Strange one, I have redone the codelist. It needs a second check, which I can ask @chrisjwood16 to do tomorrow.

I've 'diff'ed the two different codelists, and the updated VMPs are there.
https://www.opencodelists.org/codelist/user/speed-vm/antidepressants-for-pain-indication-dmd/1e769556/diff/60cf6481/

Link to codelist here
https://www.opencodelists.org/codelist/user/speed-vm/antidepressants-for-pain-indication-dmd/1e769556/

**Comment by alschaffer** [comment]
Thank you !

The issue is that dmd codelists are static based on when they were generated, and the BNF mapping was recently updated, which is why the new codelist has extra codes. OpenCodelists automatically updates BNF codelists (to account for codelist rot and other mapping changes), but _not_ dmd codelists. So essentially dmd codelists need to updated manually on a regular basis to ensure they are up to date. 

[Apologies if you already knew this but I just discovered this on Friday and had to go and update all the dmd codelists I had used in my projects...]

**Comment by speed-vm** [comment]
@alschaffer That's really helpful, thank you!

**Comment by alschaffer** [comment]
@speed-vm More accurately, OpenCodelists updates dmd codelists for changes in VMP mappings, but not BNF mappings. But if there are BNF mapping changes you probably should update the BNF code list too anyway. I think, it's complicated... https://bennettoxford.slack.com/archives/C33TWNQ1J/p1708099645797239

**Comment by alschaffer** [comment]
Looks good to me - I am happy to approve.

**Comment by speed-vm** [comment]
@alschaffer Final codelist [here](https://www.opencodelists.org/codelist/opensafely/antidepressants-for-pain-indication-dmd/1e769556/#full-list)
