### ISSUE TITLE
*MEDICATION*: Opioids for analgesia

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#288]
### User requirements

A codelist is needed of all opioids used for analgesia (any route) excluding cough suppression, motility, general anaesthesia, opiate use disorder - this is for a project looking at opioid prescribing for patients on hospital waiting lists.

### Sensitivity versus specificity

The codelist should contain all opioids likely used for analgesia including where in combination with other drugs.

### Relevant definitions or links to important reference sources

https://bnf.nice.org.uk/treatment-summaries/analgesics/

### Coding system

dm+d

### Existing relevant codelists

Nil

### Search terms / synonyms / search strategy

Opioid analgesics (040702)
Codeine
Co-codamol
Dihydrocodeine
Co-dydramol
Dextropropoxyphene
Co-proxamol

### Inclusion criteria for codes

all opioids used for analgesia (any route)

### Exclusion criteria for codes

excluding cough suppression, motility, general anaesthesia, opiate use disorder

**Comment by chrisjwood16** [comment]
Draft codelist created by @alschaffer: https://www.opencodelists.org/codelist/user/anschaf/opioids-for-analgesia/60d8cd7e/

**Comment by chrisjwood16** [comment]
@alschaffer The following items appear to have been excluded from the draft codelist - not clear why - suggest include unless specific reason:
![image](https://github.com/opensafely/codelist-development/assets/96439159/c9f594af-d504-4c3e-9b12-ade1b035a87e)

**Comment by chrisjwood16** [comment]
@alschaffer - happy to now approve this as accurate. Please can you add metadata/sign off info and publish.

**Comment by alschaffer** [comment]
Done https://www.opencodelists.org/codelist/user/anschaf/opioids-for-analgesia/747957ca/
