### ISSUE TITLE
*MEDICATION*: Codeine for analgesia

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#289]
### User requirements

A codelist is needed for codeine for analgesia (excludes cough suppression) - this is for a project looking at opioid prescribing for patients on hospital waiting lists.

### Sensitivity versus specificity

Only codeine or codeine containing combination products

### Coding system

dm+d

### Existing relevant codelists

Nil

### Search terms / synonyms / search strategy

Codeine

### Inclusion criteria for codes

Codeine containing products

### Exclusion criteria for codes

Products listed under BNF Chapter 01: Gastro-Intestinal System
Products listed under BNF Chapter 03: Respiratory System
Products containing dihydrocodeine (not codeine)

**Comment by chrisjwood16** [comment]
Draft codelist created by @alschaffer: https://www.opencodelists.org/codelist/user/anschaf/codeine-for-pain/3798da85/

**Comment by chrisjwood16** [comment]
@alschaffer This codelist includes codes for dihydrocodeine combination products but not dihydrocodeine alone. Should remove co-dydramol products from this list (or if intentional update inclusion/exclusion above accordingly).
![image](https://github.com/opensafely/codelist-development/assets/96439159/5b4f5b4a-9e59-4d7c-bc0c-750d53017af5)

**Comment by alschaffer** [comment]
Thanks, you're right, that is an error. I will take it out.

**Comment by chrisjwood16** [comment]
@alschaffer - happy to now approve this as accurate. Please can you add metadata/sign off info and publish (if needed).

**Comment by alschaffer** [comment]
Done
