### ISSUE TITLE
*CONDITION* Intellectual Disability 

### ISSUE THREAD

**Issue by johntaz** [opensafely/codelist-development#29]
Intellectual disability code list for risk prediction work. Candidate CTV3 list below
[CTV3_ID_Raw.xlsx](https://github.com/opensafely/codelist-development/files/4912007/CTV3_ID_Raw.xlsx)

**Comment by johntaz** [comment]
[CTV3_ID_v2.0.xlsx](https://github.com/opensafely/codelist-development/files/4994793/CTV3_ID_v2.0.xlsx)

Updated based on discussion with Stephen Evans suggesting "All the Down’s test codes are not evidence of disability and I don’t think should be included. There are +ve Downs codes & Trisomy 21 etc which are there and should be included."


@StatsFizz

**Comment by brianmackenna** [comment]
Separately we have derived a codelist from the [QoF learning disability register and it is available here](https://codelists.opensafely.org/codelist/opensafely/learning-disabilities/2020-07-06/#full-list). Developing codelists where a QoF register already exists has been discussed on a few morning calls.

We need 
a) check the QoF register derived list to ensure it looks ok and no errors e.g. from copy and paste
b) check the differences between QoF list and list developed by @johntaz 
c) selection of the list will be dependent on the study in question so we need to think about descriptions to make clear the distinction.

**Comment by johntaz** [comment]
[Copy of CTV3_ID_v2.0_BN_RH.xlsx](https://github.com/opensafely/codelist-development/files/5135791/Copy.of.CTV3_ID_v2.0_BN_RH.xlsx)

This has been reviewed by Brian Nicholson and Richard Hobbs.

**Comment by johntaz** [comment]
@Bengoldacre @StatsFizz 

Ben Goldacre reviewed discrepancies 
[CTV3_ID_v3.0.xlsx](https://github.com/opensafely/codelist-development/files/5135878/CTV3_ID_v3.0.xlsx)
