### ISSUE TITLE
*MEDICATION*: Tramadol

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#290]
### User requirements

A codelist is needed for tramadol (all routes) - this is for a project looking at opioid prescribing for patients on hospital waiting lists.

### Sensitivity versus specificity

Tramadol products and tramadol containing combination products only

### Coding system

dm+d

### Existing relevant codelists

Nil

### Search terms / synonyms / search strategy

Tramadol

### Inclusion criteria for codes

Tramadol products and tramadol containing combination products only

**Comment by alschaffer** [comment]
Done
