### ISSUE TITLE
*MEDICATION*: Weak opioids

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#291]
### User requirements

A codelist is needed of all weak opioids used for analgesia (any route) excluding cough suppression, motility, general anaesthesia, opiate use disorder - this is for a project looking at opioid prescribing for patients on hospital waiting lists.
This will use the BNF definition of weak opioids https://bnf.nice.org.uk/treatment-summaries/analgesics/

### Sensitivity versus specificity

All weak opioids

### Relevant definitions or links to important reference sources

BNF definition of weak opioids - https://bnf.nice.org.uk/treatment-summaries/analgesics/:
- codeine
- dihydrocodeine
- meptazinol
Plus would also include dextropropoxyphene as weak opioid as detailed here - https://www.sciencedirect.com/science/article/pii/S000709122200126X#bib17

### Coding system

dm+d

### Existing relevant codelists

Nil

### Search terms / synonyms / search strategy

- codeine
- dihydrocodeine
- meptazinol
- dextropropoxyphene

### Inclusion criteria for codes

Any of:
- codeine
- dihydrocodeine
- meptazinol
- dextropropoxyphene

**Comment by chrisjwood16** [comment]
Draft codelist: https://www.opencodelists.org/codelist/user/chriswood/weak-opioids/3fa7b16a/

**Comment by chrisjwood16** [comment]
Draft codelist by @alschaffer: https://www.opencodelists.org/codelist/user/anschaf/weak-opioids/4f1ae69c/

**Comment by chrisjwood16** [comment]
@alschaffer - I would also include these under weak opioids:
![image](https://github.com/opensafely/codelist-development/assets/96439159/b5767029-a62d-47c1-96b6-b2139c8e620a)

Dihydrocodeine as detailed in BNF
Meptazinol as detailed in BNF
Dextropropoxyphene as detailed [here](https://www.sciencedirect.com/science/article/pii/S000709122200126X#bib17) - BNF don't specify but probably as no longer licensed in the UK.

**Comment by alschaffer** [comment]
There is an updated version of that codelist here, which does include those medications: https://www.opencodelists.org/codelist/user/anschaf/weak-opioids/1cfc0032/ 

I accidentally published the older codelist, so can't delete it. If I publish this new version, will it overwrite the old version?

**Comment by chrisjwood16** [comment]
@alschaffer - happy to approve this latest version as accurate. Please can you add metadata/sign off info and publish.

I don't think it will replace the previously published version - I think you will need to ask tech-support to delete once published.

**Comment by alschaffer** [comment]
Done https://www.opencodelists.org/codelist/user/anschaf/weak-opioids/1cfc0032/
