### ISSUE TITLE
*MEDICATION*: Strong opioids

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#292]
### User requirements

A codelist is needed of all strong opioids used for analgesia (any route) excluding cough suppression, motility, general anaesthesia, opiate use disorder - this is for a project looking at opioid prescribing for patients on hospital waiting lists.
This will use the BNF definition of strong opioids https://bnf.nice.org.uk/treatment-summaries/analgesics/

### Sensitivity versus specificity

All strong opioids

### Relevant definitions or links to important reference sources

BNF definition of weak/strong opioids - https://bnf.nice.org.uk/treatment-summaries/analgesics/:

### Coding system

dm+d

### Existing relevant codelists

Nil

### Search terms / synonyms / search strategy

Strategy - include all opioids identified in the codelist [Opioids for analgesia](https://github.com/opensafely/codelist-development/issues/288) 
But then exclude any identified in the codelist [Weak opioids](https://github.com/opensafely/codelist-development/issues/291)

### Inclusion criteria for codes

Any strong opioid

### Exclusion criteria for codes

Weak opioids

**Comment by alschaffer** [comment]
@chrisjwood16 That looks really weird, not sure what happened? But if you have an existing codelist I'll just use that one.

**Comment by alschaffer** [comment]
Ok I know what happened - that was an old version that I had accidentally published, and there was another version that was under review that made more sense.

**Comment by chrisjwood16** [comment]
Are you happy to go down as second check for the one I created?

**Comment by alschaffer** [comment]
@chrisjwood16 Should these two be removed? 
![image](https://github.com/opensafely/codelist-development/assets/37759997/c9748fdd-5a9b-47fe-8f0c-abf32311600a)

**Comment by chrisjwood16** [comment]
Good spot - removed in this version:
https://www.opencodelists.org/codelist/user/chriswood/strongopioidsCW/25d18aa6/

**Comment by alschaffer** [comment]
Ok, looks good to me. Happy to approve. @chrisjwood16

**Comment by chrisjwood16** [comment]
Published:
BNF format:
https://www.opencodelists.org/codelist/opensafely/strongopioidsCW/25d18aa6/

dmd format:
https://www.opencodelists.org/codelist/opensafely/strongopioidsCW-dmd/28e2efe5/
