### ISSUE TITLE
*CONDITION* Cystic fibrosis

### ISSUE THREAD

**Issue by cminassian** [opensafely/codelist-development#30]
Cystic fibrosis codelist for risk prediction work.

The chronic respiratory disease codelist (version 2020-04-10, excluding asthma) currently include cystic fibrosis codes. For the risk prediction work we want to split this into 2 separate codelists to identify patients with:
-	cystic fibrosis
-	respiratory disease other than asthma or cystic fibrosis

After discussions with Helen and Laurie, I’ve added a flag (1/2 for definite/possible cystic fibrosis) to the chronic respiratory disease codelist:
[Copy of opensafely-chronic-respiratory-disease-2020-04-10_CFflag_10072020_LT.xlsx](https://github.com/opensafely/codelist-development/files/4914296/Copy.of.opensafely-chronic-respiratory-disease-2020-04-10_CFflag_10072020_LT.xlsx)

@laurietomlinson, @hmcd can you confirm which - if any - of the 'possible' codes to include in the final cystic fibrosis list? 
Also - there is one screening code for cystic fibrosis (Y2708, highlighted): presumably we want to exclude this from both lists?

**Comment by amirmehrkar** [comment]
As another clinical review: 

@cminassian @laurietomlinson @hmcd if the purpose is explicitly to create a CF codelist, then I would agree with @cminassian categorization and remove all the 2 items including the screening code.

**Comment by hmcd** [comment]
I wondered the same as @amirmehrkar  - possibly the way to decide would be to ask Jenni Q whether people with these conditions were advised to shield the same as CF patients? I'd have expected them to share a similar risk, but lack the clinical expertise to be sure.

I also strongly think we should update the chronic respiratory disease list in all ongoing studies to remove the screening code - this may be including newborn babies receiving screening in our chronic respiratory disease patient list.

**Comment by cminassian** [comment]
@amirmehrkar @hmcd @laurietomlinson Jenni Q advised that codes flagged as possible CF (PCD and other related codes) in the chronic respiratory disease codelist below can be grouped as CF and associated diseases, as these patients will be treated in the same way as CF and advised to shield. Can these now be signed off? @laurietomlinson

DEFINITION: Patients who have a Read v3 code ever on their medical records for i) cystic fibrosis (and associated diseases such as Primary ciliary dyskinesia), ii) other chronic respiratory disease (excluding asthma and cystic fibrosis) 

CODE LISTS: 
i) Final CTV3 cystic fibrosis codelist: 
[CTV3-cystic-fibrosis-17072020.xlsx](https://github.com/opensafely/codelist-development/files/4939660/CTV3-cystic-fibrosis-17072020.xlsx)

ii) Final CTV3 other chronic respiratory disease codelist:
[CTV3-other-chronic-respiratory-disease-17072020.xlsx](https://github.com/opensafely/codelist-development/files/4939668/CTV3-other-chronic-respiratory-disease-17072020.xlsx)

These lists are subsets of the original chronic respiratory disease codelist: [Copy of opensafely-chronic-respiratory-disease-2020-04-10_CFflag_10072020_LT.xlsx](https://github.com/opensafely/codelist-development/files/4939658/Copy.of.opensafely-chronic-respiratory-disease-2020-04-10_CFflag_10072020_LT.xlsx)
split by @cminassian after clinical review and discussion with @hmcd @laurietomlinson @amirmehrkar

i) (cystic fibrosis) includes codes flagged as definite/possible cystic fibrosis (CF=1 or 2) in the chronic respiratory disease codelist 
ii) (other chronic respiratory) includes all remaining codes (CF=0) in the chronic respiratory disease codelist minus one screening code: Y2708 Cystic fibrosis screening test.

NOTE: the screening code currently remains in the original chronic respiratory disease list and will need to be removed. 

FLEXIBILITY NEEDED BETWEEN STUDIES: 

EFFECTS ON COHORT SELECTION: 

POTENTIAL BIASES: Because patients with cystic fibrosis are looked after in specialist clinics, ascertainment of cystic fibrosis in primary care records is likely to be incomplete. 

CLINICAL SIGN OFF & DATE: 

EPIDEMIOLOGY SIGN OFF & DATE: Caroline Minassian @cminassian 17/07/2020

SHARED WITH WIDER TEAM: 

FINAL SIGN OFF DATE (and apply label)
