### ISSUE TITLE
*MEDICATION*: Pharmacy First - Impetigo treatment

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#300]
### User requirements

This codelist is used to identify supply of any medication included in the Pharmacy First Patient Group Directions for treatment of impetigo.

### Sensitivity versus specificity

Specific to only the strength/formulations included in the PGDs for impetigo.

### Relevant definitions or links to important reference sources

PGDs: 
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3a.-Impetigo-hydrogen-peroxide-cream-protocol-Pharmacy-First.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3b.-Impetigo-fusidic-acid-cream-patient-group-direction-Pharmacy-First.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3c.-Impetigo-flucloxacillin-patient-group-direction-Pharmacy-First.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3d.-Impetigo-clarithromycin-patient-group-direction-Pharmacy-First.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3e.-Impetigo-erythromycin-patient-group-direction-Pharmacy-First.pdf

### Coding system

dm+d

### Existing relevant codelists

N/A

### Search terms / synonyms / search strategy
- Crystacide
- Hydrogen peroxide
- Fusidic acid
- Flucloxacillin
- Clarithromycin
- Erythromycin

### Inclusion criteria for codes

- Hydrogen peroxide 1% (10mg/1g) cream (e.g. Crystacide® 1% cream)
- Fusidic acid 20mg/g (2%) cream
- Flucloxacillin 250mg capsules
- Flucloxacillin 500mg capsules
- Flucloxacillin 125mg/5mL oral solution (or oral suspension)
- Flucloxacillin 125mg/5mL sugar free oral solution (or oral suspension)
- Flucloxacillin 250mg/5mL oral solution (or oral suspension)
- Flucloxacillin 250mg/5mL sugar free oral solution (or oral suspension)
- Clarithromycin 250mg tablets
- Clarithromycin 125mg/5mL oral suspension (or oral solution)
- Clarithromycin 250mg/5mL oral suspension (or oral solution)
- Erythromycin 250mg tablets
- Erythromycin 250mg gastro-resistant tablets
- Erythromycin 500mg tablets
- Erythromycin 125mg/5mL oral suspension (or oral solution)
- Erythromycin 125mg/5mL sugar free oral suspension (or oral solution)
- Erythromycin 250mg/5mL oral suspension (or oral solution)
- Erythromycin 250mg/5mL sugar free oral suspension (or oral solution)
- Erythromycin 500mg/5mL oral suspension (or oral solution)
- Erythromycin 500mg/5mL sugar free oral suspension (or oral solution)

### Exclusion criteria for codes
Strengths/formulations not listed above.

### Borderline cases
Clarithromycin granules for oral solution, erythromycin capsules - excluded as form not included in PGD.

### Final codelist

Published:
BNF code format:
https://www.opencodelists.org/codelist/opensafely/pharmacy-first-impetigo-treatment/099de038/

dm+d code format:
https://www.opencodelists.org/codelist/opensafely/pharmacy-first-impetigo-treatment-dmd/708e6d02/

**Comment by a-d-brown** [comment]
Consider adding:
- Erythroped A 500mg tablets (0501050H0BDAIAE)
- Erythroped Forte SF 500mg/5ml oral suspension (0501050H0BDAPAN)
- Erythroped PI SF 125mg/5ml oral suspension (0501050H0BDANAL)
- Erythroped SF 250mg/5ml oral suspension (0501050H0BDAMAM)

There's limited prescribing of these items (in most cases none), and none of them are listed in EMC, so I think they're unlikely to be very important. But probably still makes sense to add for completeness, and consistency in approach.

On the other hand, if the preference is to exclude products where there is no prescribing and they're not listed in EMC, then there's probably a few other items we could remove from the codelist such as:
- Rommix 250 EC tablets (0501050C0BIAAAB)

Otherwise, all looks good to me. @chrisjwood16

**Comment by chrisjwood16** [comment]
@a-d-brown  Not sure what happened there. They should have been included - updated version here:
https://www.opencodelists.org/codelist/user/chriswood/pharmacy-first-impetigo-treatment/099de038/

**Comment by a-d-brown** [comment]
@chrisjwood16 - checked, all correct.

**Comment by chrisjwood16** [comment]
As [explained here](https://github.com/opensafely/pharmacy-first/issues/104), due to complexities in the data we need to build this codelist directly in dmd to ensure we include products which don't have a BNF code.

We can use a view which contains required dmd fields and then query this to select products matching our inclusion criteria:
- Hydrogen peroxide 1% (10mg/1g) cream (e.g. Crystacide® 1% cream)
- Fusidic acid 20mg/g (2%) cream
- Flucloxacillin 250mg capsules
- Flucloxacillin 500mg capsules
- Flucloxacillin 125mg/5mL oral solution (or oral suspension)
- Flucloxacillin 125mg/5mL sugar free oral solution (or oral suspension)
- Flucloxacillin 250mg/5mL oral solution (or oral suspension)
- Flucloxacillin 250mg/5mL sugar free oral solution (or oral suspension)
- Clarithromycin 250mg tablets
- Clarithromycin 125mg/5mL oral suspension (or oral solution)
- Clarithromycin 250mg/5mL oral suspension (or oral solution)
- Erythromycin 250mg tablets
- Erythromycin 250mg gastro-resistant tablets
- Erythromycin 500mg tablets
- Erythromycin 125mg/5mL oral suspension (or oral solution)
- Erythromycin 125mg/5mL sugar free oral suspension (or oral solution)
- Erythromycin 250mg/5mL oral suspension (or oral solution)
- Erythromycin 250mg/5mL sugar free oral suspension (or oral solution)
- Erythromycin 500mg/5mL oral suspension (or oral solution)
- Erythromycin 500mg/5mL sugar free oral suspension (or oral solution)

```
SELECT DISTINCT
dmd_type, dmd_id, dmd_name, bnf_code
FROM
`chris.union_amp_vmp`
WHERE
(
  vtm = 'Hydrogen peroxide'
  AND
  formroute IN ('cream.cutaneous')
  AND
  strength_num = 10 -- 10 here corresponds to 1% cream
)
OR
(
  vtm = 'Fusidic acid'
  AND
  formroute IN ('cream.cutaneous')
  AND
  strength_num = 20 -- 20 here corresponds to 2% cream
)
OR
(
  vtm = 'Flucloxacillin'
  AND formroute IN ('capsule.oral') 
  AND strength_num IN (250, 500) 
)
OR
(
  vtm = 'Flucloxacillin'
  AND formroute IN ('solution.oral', 'suspension.oral')
  AND (((5/strength_den)*strength_num) IN (125, 250)) -- strength is often expressed as mg/ml - this calculation converts to dose per 5ml as expressed in inclusion criteria
)
OR
(
  vtm = 'Clarithromycin'
  AND formroute IN ('tablet.oral')
  AND strength_num IN (250)
)
OR
(
  vtm = 'Clarithromycin' 
  AND formroute IN ('solution.oral', 'suspension.oral')
  AND (((5/strength_den)*strength_num) IN (125, 250)) -- strength is often expressed as mg/ml - this calculation converts to dose per 5ml as expressed in inclusion criteria
)
OR
(
  ingredient = 372694001 -- use ingredient code for erythromycin base substance here not vtm as a number of different erythromycin salts
  AND
  ingredient_count = 1
  AND
  formroute IN ('tablet.oral', 'tabletgastro-resistant.oral')
  AND
  strength_num IN (250, 500)
)
OR
(
  ingredient = 372694001 -- use ingredient code for erythromycin base substance here not vtm as a number of different erythromycin salts
  AND
  ingredient_count = 1
  AND
  formroute IN ('solution.oral', 'suspension.oral')
  AND 
  (((5/strength_den)*strength_num) IN (125, 250, 500)) -- strength is often expressed as mg/ml - this calculation converts to dose per 5ml as expressed in inclusion criteria
)
```

[PF_treatment_impetigo.csv](https://github.com/user-attachments/files/18496632/PF_treatment_impetigo.csv)

**Comment by chrisjwood16** [comment]
Checked against existing codelist. These are in the new codelist not in previous version:
dmd_type,dmd_id,dmd_name,bnf_code
VMP,22751511000001108,Flucloxacillin sodium 125mg/5ml oral suspension,
AMP,14222611000001101,Erythrocin 500 tablets (Sigma Pharmaceuticals Plc),
AMP,14223111000001103,Erythroped A 500mg tablets (Sigma Pharmaceuticals Plc),
AMP,17899311000001109,Erythromycin ethyl succinate 500mg tablets (Sigma Pharmaceuticals Plc),
AMP,37369311000001108,Erythrocin 250 tablets (CST Pharma Ltd),
AMP,37369811000001104,Erythrocin 500 tablets (CST Pharma Ltd),
AMP,44158611000001102,Flucloxacillin 250mg capsules (Flamingo Pharma (UK) Ltd),
AMP,42544011000001102,Flucloxacillin 500mg capsules (Flamingo Pharma (UK) Ltd),0501012G0AAABAB
AMP,43990411000001108,Flucloxacillin 500mg capsules (Crescent Pharma Ltd),0501012G0AAABAB
AMP,42816811000001105,Clarithromycin 250mg tablets (Drugsrus Ltd),0501050B0AAAAAA
AMP,42455811000001101,Clarithromycin 250mg tablets (Krka UK Ltd),0501050B0AAAAAA
AMP,22878811000001100,Erythrocin 500 tablets (Waymade Healthcare Plc),
AMP,5264311000001103,Fucidin 20mg/g cream (Waymade Healthcare Plc),
AMP,5286611000001101,Clarithromycin 125mg/5ml oral suspension (Dowelhurst Ltd),
AMP,5292911000001109,Fucidin 20mg/g cream (Dowelhurst Ltd),
AMP,5298511000001100,Klaricid Paediatric 125mg/5ml oral suspension (Dowelhurst Ltd),
AMP,5300211000001105,Klaricid Paediatric 250mg/5ml oral suspension (Dowelhurst Ltd),
AMP,5377011000001108,Klaricid 250mg tablets (Waymade Healthcare Plc),
AMP,5464111000001104,Fusidic acid 2% cream (Dowelhurst Ltd),
AMP,5514211000001102,Clarithromycin 250mg tablets (Dowelhurst Ltd),
AMP,5541711000001100,Erythrocin 500 tablets (Dowelhurst Ltd),
AMP,5543211000001106,Erythroped A 500mg tablets (Dowelhurst Ltd),
AMP,5551011000001104,Klaricid 250mg tablets (Dowelhurst Ltd),
AMP,10536411000001109,Erythroped A 500mg tablets (Waymade Healthcare Plc),
AMP,10833311000001107,Clarithromycin 125mg/5ml oral suspension (Waymade Healthcare Plc),
AMP,10833511000001101,Clarithromycin 250mg/5ml oral suspension (Waymade Healthcare Plc),
AMP,13225711000001103,Clarithromycin 250mg/5ml oral suspension (Dowelhurst Ltd),
AMP,13875411000001102,Erythrocin 500 tablets (DE Pharmaceuticals),
AMP,13881811000001105,Fucidin 20mg/g cream (DE Pharmaceuticals),
AMP,14244911000001100,Fucidin 20mg/g cream (Sigma Pharmaceuticals Plc),
AMP,14735011000001105,Klaricid 250mg tablets (Sigma Pharmaceuticals Plc),
AMP,16172811000001109,Erythroped A 500mg tablets (Lexon (UK) Ltd),
AMP,16544311000001103,Erythrocin 500 tablets (Stephar (U.K.) Ltd),
AMP,16572211000001101,Erythroped A 500mg tablets (Mawdsley-Brooks & Company Ltd),
AMP,17503311000001109,Erythrocin 500 tablets (Mawdsley-Brooks & Company Ltd),
AMP,18056411000001108,Erythrocin 500 tablets (Lexon (UK) Ltd),
AMP,18156111000001105,Fucidin 20mg/g cream (Mawdsley-Brooks & Company Ltd),
AMP,18257211000001100,Erythrocin 500 tablets (Necessity Supplies Ltd),
AMP,18257511000001102,Erythroped A 500mg tablets (Necessity Supplies Ltd),
AMP,18271111000001101,Klaricid 250mg tablets (Necessity Supplies Ltd),
AMP,22706111000001100,Flucloxacillin sodium 125mg/5ml oral suspension (Medreich Plc),
AMP,24099111000001103,Erythromycin 250mg gastro-resistant tablets (Waymade Healthcare Plc),

No codes in previous version which aren't in the new version.

**Comment by a-d-brown** [comment]
Checked, all looks correct.

**Comment by chrisjwood16** [comment]
Final version:
https://www.opencodelists.org/codelist/opensafely/pharmacy-first-impetigo-treatment-full-dmd-codelist/1ab1d9e9/

**Comment by chrisjwood16** [comment]
Updated PGDs reviewed:
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3a.-impetigo-hydrogen-peroxide-cream-protocol-pharmacy-first.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3b.-Impetigo-fusidic-acid-cream-patient-group-direction-Pharmacy-First.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3c.-impetigo-flucloxacillin-patient-group-direction-pharmacy-first.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3d.-impetigo-clarithromycin-patient-group-direction-pharmacy-first.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3e.-impetigo-erythromycin-patient-group-direction-pharmacy-first.pdf

These products have been removed from latest PGDs:
Erythromycin 500mg/5mL oral suspension (or oral solution)
Erythromycin 500mg/5mL sugar free oral suspension (or oral solution)

Decision made to keep them in the codelist to capture any use prior to PGD update.

Updated codelist:
https://www.opencodelists.org/codelist/opensafely/pharmacy-first-impetigo-treatment-full-dmd-codelist/20051342/

**Comment by a-d-brown** [comment]
Checked, all correct.
