### ISSUE TITLE
*MEDICATION*: Pharmacy First - Infected insect bites treatment

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#302]
### User requirements

This codelist is used to identify supply of any medication included in the Pharmacy First Patient Group Directions for treatment of infected insect bites.

### Sensitivity versus specificity

Specific to only the strength/formulations included in the PGDs for infected insect bites.

### Relevant definitions or links to important reference sources

PGDs: 
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4a.-Infected-insect-bites-flucloxacillin-patient-group-direction-Pharmacy-First.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4b.-Infected-insect-bites-clarithromycin-patient-group-direction-Pharmacy-First.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4c.-Infected-insect-bites-erythromycin-patient-group-direction-Pharmacy-First.pdf

### Coding system

dm+d

### Existing relevant codelists

N/A

### Search terms / synonyms / search strategy

- Flucloxacillin
- Clarithromycin
- Erythromycin

### Inclusion criteria for codes

- Flucloxacillin 250mg capsules
- Flucloxacillin 500mg capsules
- Flucloxacillin 125mg/5mL oral solution (or oral suspension)
- Flucloxacillin 125mg/5mL sugar free oral solution (or oral suspension)
- Flucloxacillin 250mg/5mL oral solution (or oral suspension)
- Flucloxacillin 250mg/5mL sugar free oral solution (or oral suspension)
- Clarithromycin 250mg tablets
- Clarithromycin 500mg tablets
- Clarithromycin 125mg/5mL oral suspension (or oral solution)
- Clarithromycin 250mg/5mL oral suspension (or oral solution)
- Erythromycin 250mg tablets
- Erythromycin 250mg gastro-resistant tablets
- Erythromycin 500mg tablets
- Erythromycin 125mg/5mL oral suspension (or oral solution)
- Erythromycin 125mg/5mL sugar free oral suspension (or oral solution)
- Erythromycin 250mg/5mL oral suspension (or oral solution)
- Erythromycin 250mg/5mL sugar free oral suspension (or oral solution)
- Erythromycin 500mg/5mL oral suspension (or oral solution)
- Erythromycin 500mg/5mL sugar free oral suspension (or oral solution)

### Exclusion criteria for codes
Strengths/formulations not listed above.

### Borderline cases
Clarithromycin granules for oral solution, erythromycin capsules - excluded as form not included in PGD.

### Final codelist

Published.
BNF code format: https://www.opencodelists.org/codelist/opensafely/pharmacy-first-infected-insect-bites-treatment/5a31b9c3/
dm+d format: https://www.opencodelists.org/codelist/opensafely/pharmacy-first-infected-insect-bites-treatment-dmd/2812d359/

**Comment by a-d-brown** [comment]
Consider adding:
- Flucloxacillin 250mg capsules (0501012G0AAAAAA)

Otherwise all looks good. @chrisjwood16

**Comment by chrisjwood16** [comment]
Good spot. Missed in error - added now:
https://www.opencodelists.org/codelist/user/chriswood/pharmacy-first-infected-insect-bites-treatment/5a31b9c3/

**Comment by chrisjwood16** [comment]
Published.
BNF code format: https://www.opencodelists.org/codelist/opensafely/pharmacy-first-infected-insect-bites-treatment/5a31b9c3/
dm+d format: https://www.opencodelists.org/codelist/opensafely/pharmacy-first-infected-insect-bites-treatment-dmd/2812d359/

**Comment by chrisjwood16** [comment]
As [explained here](https://github.com/opensafely/pharmacy-first/issues/104), due to complexities in the data we need to build this codelist directly in dmd to ensure we include products which don't have a BNF code.

We can use a view which contains required dmd fields and then query this to select products matching our inclusion criteria:

- Flucloxacillin 250mg capsules
- Flucloxacillin 500mg capsules
- Flucloxacillin 125mg/5mL oral solution (or oral suspension)
- Flucloxacillin 125mg/5mL sugar free oral solution (or oral suspension)
- Flucloxacillin 250mg/5mL oral solution (or oral suspension)
- Flucloxacillin 250mg/5mL sugar free oral solution (or oral suspension)
- Clarithromycin 250mg tablets
- Clarithromycin 500mg tablets
- Clarithromycin 125mg/5mL oral suspension (or oral solution)
- Clarithromycin 250mg/5mL oral suspension (or oral solution)
- Erythromycin 250mg tablets
- Erythromycin 250mg gastro-resistant tablets
- Erythromycin 500mg tablets
- Erythromycin 125mg/5mL oral suspension (or oral solution)
- Erythromycin 125mg/5mL sugar free oral suspension (or oral solution)
- Erythromycin 250mg/5mL oral suspension (or oral solution)
- Erythromycin 250mg/5mL sugar free oral suspension (or oral solution)
- Erythromycin 500mg/5mL oral suspension (or oral solution)
- Erythromycin 500mg/5mL sugar free oral suspension (or oral solution)

```
SELECT DISTINCT
dmd_type, dmd_id, dmd_name, bnf_code
FROM
`chris.union_amp_vmp`
WHERE
(
  vtm = 'Flucloxacillin'
  AND formroute IN ('capsule.oral') 
  AND strength_num IN (250, 500) 
)
OR
(
  vtm = 'Flucloxacillin'
  AND formroute IN ('solution.oral', 'suspension.oral')
  AND (((5/strength_den)*strength_num) IN (125, 250)) -- strength is often expressed as mg/ml - this calculation converts to dose per 5ml as expressed in inclusion criteria
)
OR
(
  vtm = 'Clarithromycin'
  AND formroute IN ('tablet.oral')
  AND strength_num IN (250, 500)
)
OR
(
  vtm = 'Clarithromycin' 
  AND formroute IN ('solution.oral', 'suspension.oral')
  AND (((5/strength_den)*strength_num) IN (125, 250)) -- strength is often expressed as mg/ml - this calculation converts to dose per 5ml as expressed in inclusion criteria
)
OR
(
  ingredient = 372694001 -- use ingredient code for erythromycin base substance here not vtm as a number of different erythromycin salts
  AND
  ingredient_count = 1
  AND
  formroute IN ('tablet.oral', 'tabletgastro-resistant.oral')
  AND
  strength_num IN (250, 500)
)
OR
(
  ingredient = 372694001 -- use ingredient code for erythromycin base substance here not vtm as a number of different erythromycin salts
  AND
  ingredient_count = 1
  AND
  formroute IN ('solution.oral', 'suspension.oral')
  AND 
  (((5/strength_den)*strength_num) IN (125, 250, 500)) -- strength is often expressed as mg/ml - this calculation converts to dose per 5ml as expressed in inclusion criteria
)
```

[PF_treatment_infected_insect_bites.csv](https://github.com/user-attachments/files/18496668/PF_treatment_infected_insect_bites.csv)

**Comment by chrisjwood16** [comment]
Checked against existing codelist. These are in the new codelist not in previous version:
dmd_type,dmd_id,dmd_name,bnf_code
VMP,22751511000001108,Flucloxacillin sodium 125mg/5ml oral suspension,
AMP,14222611000001101,Erythrocin 500 tablets (Sigma Pharmaceuticals Plc),
AMP,14223111000001103,Erythroped A 500mg tablets (Sigma Pharmaceuticals Plc),
AMP,17899311000001109,Erythromycin ethyl succinate 500mg tablets (Sigma Pharmaceuticals Plc),
AMP,37369311000001108,Erythrocin 250 tablets (CST Pharma Ltd),
AMP,37369811000001104,Erythrocin 500 tablets (CST Pharma Ltd),
AMP,44154311000001102,Clarithromycin 500mg tablets (Quattro Pharma Ltd),
AMP,44158611000001102,Flucloxacillin 250mg capsules (Flamingo Pharma (UK) Ltd),
AMP,42544011000001102,Flucloxacillin 500mg capsules (Flamingo Pharma (UK) Ltd),0501012G0AAABAB
AMP,43990411000001108,Flucloxacillin 500mg capsules (Crescent Pharma Ltd),0501012G0AAABAB
AMP,42816811000001105,Clarithromycin 250mg tablets (Drugsrus Ltd),0501050B0AAAAAA
AMP,42455811000001101,Clarithromycin 250mg tablets (Krka UK Ltd),0501050B0AAAAAA
AMP,42456611000001105,Clarithromycin 500mg tablets (Krka UK Ltd),0501050B0AAADAD
AMP,42830211000001104,Clarithromycin 500mg tablets (Drugsrus Ltd),0501050B0AAADAD
AMP,22878811000001100,Erythrocin 500 tablets (Waymade Healthcare Plc),
AMP,5286611000001101,Clarithromycin 125mg/5ml oral suspension (Dowelhurst Ltd),
AMP,5298511000001100,Klaricid Paediatric 125mg/5ml oral suspension (Dowelhurst Ltd),
AMP,5300211000001105,Klaricid Paediatric 250mg/5ml oral suspension (Dowelhurst Ltd),
AMP,5377011000001108,Klaricid 250mg tablets (Waymade Healthcare Plc),
AMP,5377411000001104,Klaricid 500 tablets (Waymade Healthcare Plc),
AMP,5459011000001106,Clarithromycin 500mg tablets (Dowelhurst Ltd),
AMP,5514211000001102,Clarithromycin 250mg tablets (Dowelhurst Ltd),
AMP,5541711000001100,Erythrocin 500 tablets (Dowelhurst Ltd),
AMP,5543211000001106,Erythroped A 500mg tablets (Dowelhurst Ltd),
AMP,5551011000001104,Klaricid 250mg tablets (Dowelhurst Ltd),
AMP,5551211000001109,Klaricid 500 tablets (Dowelhurst Ltd),
AMP,10536411000001109,Erythroped A 500mg tablets (Waymade Healthcare Plc),
AMP,10833311000001107,Clarithromycin 125mg/5ml oral suspension (Waymade Healthcare Plc),
AMP,10833511000001101,Clarithromycin 250mg/5ml oral suspension (Waymade Healthcare Plc),
AMP,13225711000001103,Clarithromycin 250mg/5ml oral suspension (Dowelhurst Ltd),
AMP,13875411000001102,Erythrocin 500 tablets (DE Pharmaceuticals),
AMP,14734611000001104,Klaricid 500 tablets (Sigma Pharmaceuticals Plc),
AMP,14735011000001105,Klaricid 250mg tablets (Sigma Pharmaceuticals Plc),
AMP,16172811000001109,Erythroped A 500mg tablets (Lexon (UK) Ltd),
AMP,16544311000001103,Erythrocin 500 tablets (Stephar (U.K.) Ltd),
AMP,16551711000001104,Klaricid 500 tablets (Stephar (U.K.) Ltd),
AMP,16572211000001101,Erythroped A 500mg tablets (Mawdsley-Brooks & Company Ltd),
AMP,17503311000001109,Erythrocin 500 tablets (Mawdsley-Brooks & Company Ltd),
AMP,18056411000001108,Erythrocin 500 tablets (Lexon (UK) Ltd),
AMP,18257211000001100,Erythrocin 500 tablets (Necessity Supplies Ltd),
AMP,18257511000001102,Erythroped A 500mg tablets (Necessity Supplies Ltd),
AMP,18271111000001101,Klaricid 250mg tablets (Necessity Supplies Ltd),
AMP,18271311000001104,Klaricid 500 tablets (Necessity Supplies Ltd),
AMP,22706111000001100,Flucloxacillin sodium 125mg/5ml oral suspension (Medreich Plc),
AMP,24099111000001103,Erythromycin 250mg gastro-resistant tablets (Waymade Healthcare Plc),

No codes in previous version which aren't in the new version.

**Comment by a-d-brown** [comment]
Checked, all looks correct.

**Comment by chrisjwood16** [comment]
Final version:
https://www.opencodelists.org/codelist/opensafely/pharmacy-first-infected-insect-bites-treatment-full-dmd-codelist/33c14d1e/

**Comment by chrisjwood16** [comment]
Updated PGDs reviewed:
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4a.-infected-insect-bites-flucloxacillin-patient-group-direction-pharmacy-first.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4b.-infected-insect-bites-clarithromycin-patient-group-direction-pharmacy-first.pdf
https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4c.-infected-insect-bites-erythromycin-patient-group-direction-pharmacy-first.pdf

These products have been removed from latest PGDs:
Erythromycin 500mg/5mL oral suspension (or oral solution)
Erythromycin 500mg/5mL sugar free oral suspension (or oral solution)

Decision made to keep them in the codelist to capture any use prior to PGD update.

Updated codelist:
https://www.opencodelists.org/codelist/opensafely/pharmacy-first-infected-insect-bites-treatment-full-dmd-codelist/54d6b9a2/

**Comment by a-d-brown** [comment]
Checked, all correct.
