### ISSUE TITLE
*MEDICATION*: Gabapentinoids

### ISSUE THREAD

**Issue by speed-vm** [opensafely/codelist-development#305]
### User requirements

To be used to see prescribing of gabapentinoids in the OS waiting lists project

### Sensitivity versus specificity

Should capture all formulations of pregabalin and gabapentin that might be used in the management of neuropathic pain.

### Relevant definitions or links to important reference sources

https://bnf.nice.org.uk/treatment-summaries/neuropathic-pain/
https://www.nice.org.uk/guidance/cg173

### Coding system

dm+d

### Existing relevant codelists

Updating previous codelist

### Search terms / synonyms / search strategy

Pregabalin
Gabapentin

### Final codelist

https://www.opencodelists.org/codelist/user/anschaf/gabapentinoids/6d9942ba/#full-list

**Comment by speed-vm** [comment]
@alschaffer I'm happy with this codelist.

**Comment by alschaffer** [comment]
Final published codelist here: https://www.opencodelists.org/codelist/user/anschaf/gabapentinoids/6d9942ba/
