### ISSUE TITLE
*MEDICATION*: Pharmacy First - Any PGD oral antibiotic

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#307]
### User requirements

This codelist is used to identify supply of any oral antibiotic medication included in the Pharmacy First Patient Group Directions.

### Sensitivity versus specificity

Specific to only the strength/formulations included in the PGDs for Pharmacy First (including both brands and generics).

### Relevant definitions or links to important reference sources

PGDs:
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-1a.-Urinary-tract-infection-nitrofurantoin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-1a.-Urinary-tract-infection-nitrofurantoin-patient-group-direction-Pharmacy-First.pdf)

[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3c.-Impetigo-flucloxacillin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3c.-Impetigo-flucloxacillin-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3d.-Impetigo-clarithromycin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3d.-Impetigo-clarithromycin-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3e.-Impetigo-erythromycin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-3e.-Impetigo-erythromycin-patient-group-direction-Pharmacy-First.pdf)

[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4a.-Infected-insect-bites-flucloxacillin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4a.-Infected-insect-bites-flucloxacillin-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4b.-Infected-insect-bites-clarithromycin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4b.-Infected-insect-bites-clarithromycin-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4c.-Infected-insect-bites-erythromycin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-4c.-Infected-insect-bites-erythromycin-patient-group-direction-Pharmacy-First.pdf)

[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-5a.-Sore-throat-phenoxymethylpenicillin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-5a.-Sore-throat-phenoxymethylpenicillin-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-5b.-Sore-throat-clarithromycin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-5b.-Sore-throat-clarithromycin-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-5c.-Sore-throat-erythromycin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-5c.-Sore-throat-erythromycin-patient-group-direction-Pharmacy-First.pdf)

[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-6c.-Sinusitis-phenoxymethylpenicillin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-6c.-Sinusitis-phenoxymethylpenicillin-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-6d.-Sinusitis-clairthromycin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-6d.-Sinusitis-clairthromycin-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-6e.-Sinusitis-doxycycline-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-6e.-Sinusitis-doxycycline-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-6f.-Sinusitis-erythromycin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-6f.-Sinusitis-erythromycin-patient-group-direction-Pharmacy-First.pdf)

[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-7b.-Acute-otitis-media-amoxicillin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-7b.-Acute-otitis-media-amoxicillin-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-7c.-Acute-otitis-media-clarithromycin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-7c.-Acute-otitis-media-clarithromycin-patient-group-direction-Pharmacy-First.pdf)
[https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-7d.-Acute-otitis-media-erythromycin-patient-group-direction-Pharmacy-First.pdf](https://www.england.nhs.uk/wp-content/uploads/2023/11/PRN01010-7d.-Acute-otitis-media-erythromycin-patient-group-direction-Pharmacy-First.pdf)

### Coding system

dm+d

### Existing relevant codelists

N/A

### Search terms / synonyms / search strategy

- Nitrofurantoin 
- Flucloxacillin
- Amoxicillin
- Clarithromycin
- Erythromycin
- Phenoxymethylpenicillin
- Doxycycline

### Inclusion criteria for codes

- Nitrofurantoin 50mg immediate release tablets or capsules (generic or brand)
- Nitrofurantoin 100mg modified release capsules (generic or brand)
- Flucloxacillin 250mg capsules
- Flucloxacillin 500mg capsules
- Flucloxacillin 125mg/5mL oral solution (or oral suspension)
- Flucloxacillin 125mg/5mL sugar free oral solution (or oral suspension)
- Flucloxacillin 250mg/5mL oral solution (or oral suspension)
- Flucloxacillin 250mg/5mL sugar free oral solution (or oral suspension)
- Amoxicillin 250mg capsules
- Amoxicillin 500mg capsules
- Amoxicillin 125mg/5mL oral suspension (or oral solution)
- Amoxicillin 125mg/5mL sugar free oral suspension (or oral solution)
- Amoxicillin 250mg/5mL oral suspension (or oral solution)
- Amoxicillin 250mg/5mL sugar free oral suspension (or oral solution)
- Amoxicillin 500mg/5mL sugar free oral suspension (or oral solution)
- Clarithromycin 250mg tablets
- Clarithromycin 500mg tablets
- Clarithromycin 125mg/5mL oral suspension (or oral solution)
- Clarithromycin 250mg/5mL oral suspension (or oral solution)
- Erythromycin 250mg tablets
- Erythromycin 250mg gastro-resistant tablets
- Erythromycin 500mg tablets
- Erythromycin 125mg/5mL oral suspension (or oral solution)
- Erythromycin 125mg/5mL sugar free oral suspension (or oral solution)
- Erythromycin 250mg/5mL oral suspension (or oral solution)
- Erythromycin 250mg/5mL sugar free oral suspension (or oral solution)
- Erythromycin 500mg/5mL oral suspension (or oral solution)
- Erythromycin 500mg/5mL sugar free oral suspension (or oral solution)
- Phenoxymethylpenicillin 250mg tablets
- Phenoxymethylpenicillin 125mg/5mL oral solution (or oral suspension)
- Phenoxymethylpenicillin 125mg/5mL sugar free oral solution (or oral suspension)
- Phenoxymethylpenicillin 250mg/5mL oral solution (or oral suspension)
- Phenoxymethylpenicillin 250mg/5mL sugar free oral solution (or oral suspension)
- Doxycycline 50mg capsules
- Doxycycline 100mg capsules
- Doxycycline 100mg dispersible tablets

### Exclusion criteria for codes
Strengths/formulations not listed above.

### Borderline cases
Clarithromycin granules for oral solution, erythromycin capsules - excluded as form not included in PGD.
Vibramycin Acne Pack 50mg capsules - not for this indication. Discontinued product.
Clarithromycin granules for oral suspension - excluded as not in list on PGDs

### Final codelist

Published:
BNF code format: https://www.opencodelists.org/codelist/opensafely/pharmacy-first-any-pgd-oral-antibiotic/17e25395/
dm+d code format: https://www.opencodelists.org/codelist/opensafely/pharmacy-first-any-pgd-oral-antibiotic-dmd/78a6ace4/

**Comment by a-d-brown** [comment]
Checked - all correct. @chrisjwood16

**Comment by chrisjwood16** [comment]
Published:
BNF code format: https://www.opencodelists.org/codelist/opensafely/pharmacy-first-any-pgd-oral-antibiotic/17e25395/
dm+d code format: https://www.opencodelists.org/codelist/opensafely/pharmacy-first-any-pgd-oral-antibiotic-dmd/78a6ace4/
