### ISSUE TITLE
*CONDITION* Fragility

### ISSUE THREAD

**Issue by johntaz** [opensafely/codelist-development#31]
Fragility codelist for risk prediction work 

[OpenSAFELY_eFI_Codes_Fragility.xlsx](https://github.com/opensafely/codelist-development/files/4925571/OpenSAFELY_eFI_Codes_Fragility.xlsx)

**Comment by johntaz** [comment]
DEFINITION: Codes for fragility and fractures
Variables:
(1) a binary variable denoting the presence of one of the codes at any point in the patient record.
(2) the dates of such codes.
CODE LISTS:
(1) This has been derived  from the fracture component of the eFI developed in ResearchOne and reviewed by Laurie Tomlinson  OpenSAFELY_eFI_Codes_Fragility.xlsx

**Comment by johntaz** [comment]
@StatsFizz 

Thanks @laurietomlinson 

@krishnanbhaskaran please could you review this codelist?

**Comment by krishnanbhaskaran** [comment]
I've had a look and it looks ok to me, but would suggest a clinical reviewer on the codes as I don't have the in-depth knowledge of this area.

re the definition above - by (2) the dates of such codes - what exactly would you want - earliest date, latest date?

**Comment by StatsFizz** [comment]
I think it depends on the study. For the risk prediction stuff, we're taking the most recent date to calculate "fracture in the last year". And we are only including for people 65+. So our covariate is "fracture in the last year in a 65+ adult". 

Also, I think we're after epi review from you. Laurie has already looked (& will hopefully officially sign off!).

**Comment by krishnanbhaskaran** [comment]
If you are happy with the codelist from a clinical point of view I don't have any specific epi concerns.
