### ISSUE TITLE
*MEDICATION*: Methylphenidate

### ISSUE THREAD

**Issue by a-d-brown** [opensafely/codelist-development#311]
### User requirements

The codelist will be used to identify patients who have are receiving methylphenidate to treat ADHD.
It may be compared against a list of patients who have clinical diagnoses of ADHD.
This will inform results for the [ADHD taskforce](https://www.england.nhs.uk/2024/03/nhs-to-launch-cross-sector-adhd-taskforce-to-boost-care-for-patients-in-england/#:~:text=The%20new%20taskforce%20will%20bring,to%20concerns%20around%20rising%20demand.).

### Sensitivity versus specificity

Balanced approach.

### Relevant definitions or links to important reference sources

None.

### Coding system

dm+d

### Existing relevant codelists

None.

### Search terms / synonyms / search strategy

Will search under methylphenidate at BNF chemical level and review formulations beneath that. 

### Inclusion criteria for codes

Is a formulation licenced to treat ADHD, and expectation is that it would primarily be prescribed for ADHD.

### Exclusion criteria for codes

Is a formulation not licenced to treat ADHD, or expectation is that it would primarily be not be prescribed for ADHD.

### Borderline cases

None.

### Final codelist

https://www.opencodelists.org/codelist/opensafely/methylphenidate/189f9e27/

**Comment by a-d-brown** [comment]
Draft codelist for review: https://www.opencodelists.org/codelist/user/Andrew/methylphenidate/189f9e27/#tree

**Comment by chrisjwood16** [comment]
Looks good. Happy to approve.

**Comment by orlamac** [comment]
We have updated the Methylphenidate codelist in July 2025 using the new dm+d codelist builder, by searching for the term methylphenidate.  All codes under the term dexmethylphenidate were excluded as this is not licensed in the UK.  We found 212 items which were included (the previous codelist contained 121 items.)

**Comment by a-d-brown** [comment]
@orlamac approved
