### ISSUE TITLE
*MEDICATION*: Molnupiravir

### ISSUE THREAD

**Issue by rose-higgins** [opensafely/codelist-development#315]
##### User requirements

I need a codelist to return all recorded prescriptions of molnupiravir in primary care records. This will be used to plot the recorded prescribing in primary care of all COVID-19 therapeutics. 

##### Sensitivity versus specificity

Volumes expected to be low, and drugs specific, so sensitivity to be prioritised

##### Coding system

dm+d

##### Existing relevant codelists

N/A

##### Search terms / synonyms / search strategy
Search: Molnupiravir
Identify  all molnupiravir products including brands

##### Inclusion criteria for codes
All molnupiravir products including brands

##### Exclusion criteria for codes

N/A

##### Borderline cases

N/A

##### Final codelist
BNF: https://www.opencodelists.org/codelist/user/chriswood/molnupiravir/4d093641/
dmd: https://www.opencodelists.org/codelist/opensafely/molnupiravir-dmd-2024/048d9c98/

**Comment by chrisjwood16** [comment]
Draft BNF codelist - https://www.opencodelists.org/codelist/user/chriswood/molnupiravir/4d093641/

**Comment by speed-vm** [comment]
Checking this one now

**Comment by speed-vm** [comment]
Looks good to me @rose-higgins @chrisjwood16

**Comment by chrisjwood16** [comment]
Published:
dmd: https://www.opencodelists.org/codelist/opensafely/molnupiravir-dmd-2024/048d9c98/
