### ISSUE TITLE
*MEDICATION*: Sotrovimab

### ISSUE THREAD

**Issue by rose-higgins** [opensafely/codelist-development#316]
##### User requirements

I need a codelist to return all recorded prescriptions of sotrovimab primary care records. This will be used to plot the recorded prescribing in primary care of all COVID-19 therapeutics.

##### Sensitivity versus specificity

Volumes expected to be low, and drugs specific, so sensitivity to be prioritised

##### Relevant definitions or links to important reference sources

N/A

##### Coding system

dm+d

##### Existing relevant codelists

N/A

##### Search terms / synonyms / search strategy
Search: Sotrovimab using OpenPrescribing dm+d browser
Identify all VMP/AMPs linked to sotrovimab VTM

##### Inclusion criteria for codes

Identify all VMP/AMPs linked to sotrovimab VTM

##### Exclusion criteria for codes

N/A

##### Borderline cases

N/A

##### Final codelist

https://www.opencodelists.org/codelist/opensafely/sotrovimab-dmd/395f42f8/

**Comment by chrisjwood16** [comment]
[sotrovimab.csv](https://github.com/user-attachments/files/15872934/sotrovimab.csv)

**Comment by chrisjwood16** [comment]
@speed-vm can you second check please?

**Comment by speed-vm** [comment]
This .csv looks good to me. @rose-higgins @chrisjwood16

**Comment by chrisjwood16** [comment]
Published: https://www.opencodelists.org/codelist/opensafely/sotrovimab-dmd/395f42f8/
