### ISSUE TITLE
*MEDICATION*: Remdesivir

### ISSUE THREAD

**Issue by rose-higgins** [opensafely/codelist-development#317]
##### User requirements

I need a codelist to return all recorded prescriptions of remdesivir in primary care records. This will be used to plot the recorded prescribing in primary care of all COVID-19 therapeutics.

##### Coding system

dm+d

##### Existing relevant codelists

N/A

##### Search terms / synonyms / search strategy
Search: Remdesivir using OpenPrescribing dm+d browser
Identify all VMP/AMPs linked to remdesivir VTM

##### Inclusion criteria for codes

Identify all VMP/AMPs linked to remdesivir VTM

##### Exclusion criteria for codes

N/A

##### Borderline cases

N/A

##### Final codelist

https://www.opencodelists.org/codelist/opensafely/remdesivir/204fcfc3/

**Comment by chrisjwood16** [comment]
[remdesivir.csv](https://github.com/user-attachments/files/15872978/remdesivir.csv)

| dmd_type | dmd_id             | dmd_name                                                                                         |
|----------|--------------------|--------------------------------------------------------------------------------------------------|
| VMP      | 38377211000001108  | Remdesivir 100mg powder for solution for infusion vials                                          |
| AMP      | 38737211000001107  | Veklury 100mg powder for concentrate for solution for infusion vials (Gilead Sciences Ltd)       |

**Comment by chrisjwood16** [comment]
@speed-vm can you second check please?

**Comment by speed-vm** [comment]
[remdesivir.csv](https://github.com/user-attachments/files/15872978/remdesivir.csv) looks good to me.

**Comment by chrisjwood16** [comment]
Published: https://www.opencodelists.org/codelist/opensafely/remdesivir/204fcfc3/
