### ISSUE TITLE
*MEDICATION*: Paxlovid

### ISSUE THREAD

**Issue by rose-higgins** [opensafely/codelist-development#318]
### User requirements

I need a codelist to return all recorded prescriptions of paxlovid in primary care records. This will be used to plot the recorded prescribing in primary care of all COVID-19 therapeutics.

### Sensitivity versus specificity

Volumes expected to be low, and drugs specific, so sensitivity to be prioritised

### Coding system

dm+d

### Existing relevant codelists

None

**Comment by speed-vm** [comment]
When compared with Bang's codelist there are dm+d codes without BNF codes.
Have suggested in the first instance to refer to this codelist for Paxlovid: 
https://github.com/opensafely/Paxlovid-and-sotrovimab/blob/main/codelists/bangzheng-paxlovid-dmd-0964dee3.csv

**Comment by speed-vm** [comment]
https://www.opencodelists.org/codelist/user/speed-vm/paxlovid/1d9d0fcd/#full-list
@chrisjwood16 this is returning the VMPs and AMPs. Are you able to second check pls?

**Comment by chrisjwood16** [comment]
Reviewed. I'm happy with this.

**Comment by speed-vm** [comment]
Published: https://www.opencodelists.org/codelist/opensafely/paxlovid-dmd/6b7e2962/
