### ISSUE TITLE
*DISEASE* Venous thromboembolic disease (DVT and PE)

### ISSUE THREAD

**Issue by hmcd** [opensafely/codelist-development#33]
DEFINITION: Codes for venous thromboembolic disease

Variables:
(1) a binary variable denoting the presence of one of the codes at any point in the patient record.
(2) the earliest date of such a code.

CODE LISTS:

(1) Read 2 code list from Helen Strongman and Angel Wong combined here: 
[DVT_PE_Strongman_Wong.xlsx](https://github.com/opensafely/codelist-development/files/4941087/DVT_PE_Strongman_Wong.xlsx)

have suggested not to include (1) suspected/possible codes and (2) PEs specified as air embolism or amniotic fluid embolism as would not indicate at ongoing risk of a venous clot. 

(2) SNOMED
to search
(3) map to CTV3 - to do
(4) check and refine post mapping

FLEXIBILITY NEEDED BETWEEN STUDIES: This list doesn't include air embolism or amniotic fluid embolism  - some studies of PE may wish to include these. The list includes codes for a history of DVT or PE - studies of incident DVT/PE may wish to exclude these.

EFFECTS ON COHORT SELECTION: None

POTENTIAL BIASES: None

**Comment by hmcd** [comment]
With apologies for the delay! Have searched SNOMED for deep vein thrombosis codes, and have a list here 
[SNOMED_DVT.xlsx](https://github.com/opensafely/codelist-development/files/4966368/SNOMED_DVT.xlsx)

It's got some oddly detailed codes in because some of the high level codes included, for example, haemorrhoids, so for those I had to go to the more detailed levels to keep to DVTs. I've suggested inclusion/exclusion sticking to the same principle as above of not including suspected DVT or referral to clinic. But I wasn't sure about the "enhanced services administration" codes - do they imply DVT?

Will search for PE codes next.

**Comment by hmcd** [comment]
SNOMED search for PE 
[SNOMED_PE.xlsx](https://github.com/opensafely/codelist-development/files/4969008/SNOMED_PE.xlsx)
Since we're interested in it as an indication of clotting risk, I didn't include air embolisms, fat embolisms, or amniotic fluid embolisms or suspected PE. I did assume unspecified PEs were blood clots.

So combining the lists, and dropping the codes I'd suggest not including, for mapping to CTV3 would propose:
[SNOMED_DVT_PE_included_only.xlsx](https://github.com/opensafely/codelist-development/files/4969022/SNOMED_DVT_PE_included_only.xlsx)
and
[Readv2_DVT_PE_included_only.xlsx](https://github.com/opensafely/codelist-development/files/4969030/Readv2_DVT_PE_included_only.xlsx)

**Comment by hmcd** [comment]
@alexwalkercebm @StatsFizz @johntaz Apologies - had a hectic fortnight but now back! This has been closed but not sure we have looked through the results of mapping to CTV3 to produce a CTV3 codelist - I can do that today or tomorrow if the Read 2/SNOMED have been mapped to CTV3- or is this now not needed?

**Comment by johntaz** [comment]
@hmcd The codelist has been mapped now, please could you review?
[CTV3_Raw_DVT_PE.xlsx](https://github.com/opensafely/codelist-development/files/5102168/CTV3_Raw_DVT_PE.xlsx)

**Comment by hmcd** [comment]
Have annotated this version. I suggested:

Include==1
- any venous thromboembolism of deep veins of limbs or vena cava,
- PE, thromboembolic or unspecified

Exclude==0
- PE if the code specified that it was not a blood clot (e.g. air, fat, amniotic fluid, septic) as we're interested in clotting risk
- venous thrombosis or thrombophlebitis if not specified as deep

I have some questions for @amirmehrkar...
(1) XaaBG on deep vein thrombosis care pathway. @amirmehrkar is this someone being treated for DVT, or could they just be at high risk?
(2) 14A8. H/O: [thrombo-embolism] or [embolism] or [thrombosis] - I thought that as this started with 'thromboembolism' it'd be quite a major code to choose to use for superficial thrombophlebitis. So I've suggested including it, but do you agree?
(2) cerebral venous clots - have marked as 'c' so we have them identified. My inclination would be to see those as a separate condition. The cause may be cerebral inflammation, e.g. meningitis, whereas we're looking for history of VTE as an indication of future risk of clots. @amirmehrkar do you agree or should we be including these as venous thromboembolic disease?
(3) portal vein thrombosis and mesenteric venous thrombosis - marked as 'p' (including mesenteric vein - as I think the question is the same even if it's not portal). Again, I'd be inclined to see those as a separate condition, for which the cause may be local/ liver disease e.g. HCC, rather than indicating a systemic condition where the patient is at risk of DVT/PE. @amirmehrkar do you agree or should be be including these as venous thromboembolic disease?

@johntaz please note Iist still included the codes which I'd recommend excluding, for Amir's review. Once Amir's reviewed, we'll need to actually remove the codes we don't want from the list.
[CTV3_Raw_DVT_PE_HMcomments.xlsx](https://github.com/opensafely/codelist-development/files/5102608/CTV3_Raw_DVT_PE_HMcomments.xlsx)

**Comment by amirmehrkar** [comment]
Hi @hmcd @johntaz I think this one is quite tricky because by joining DVT and PE together there is a deliberate constraint put on this codelist ie that there needs to be the ability to cause a PE from the DVT, given that a PE by definition requires an antecedent event. 

So, given that in mind, I think, answers to  your questions:

(1) - In my mind a pathway starts with suspicion of a condition and exit from the pathway if not proven. **I would remove the XaaBG and use in preference actual diagnostic codes**. We ought to have a code for a "thombotic/pe" event if the entry to the pathway proved positive. 

(2) - Yes I would include, although it would be worthwhile asking TPP / EMIS how often it is used; if very infrequently then probably not an issue and could be removed. Either way, I wouldnt personally have used it for superficial thrombophlebitis.

(3) - There are case reports (albeit rare) from googling that cerebral venous thrombosis has led to PEs; therefore, based on the constraint implied I would include them. 

(4) - Again, based on the constraint implied, I would remove these because you cannot get a PE (anatomically) from a portal vein or mesenteric venous thrombosis. (but you can from the hepatic vein). However, given infection is a cause of mesenteric vein thrombosis, and it can be lethal, I could consider including it..... I think one way to manage this is to identify this as a subset and simply justify why/why not included. I think both reasons are valid. 

(5) - The other issue I am pondering is whether inclusion of pregnancy is important? Would pregnancy not be a confounder - ie should these codes simply be removed, unless there is a specific study on pregnant women and C19 risks?

**Comment by hmcd** [comment]
Thank you Amir! 

Your suggestions on (1) and (2) sound good to me.

For (3) and (4) I don't have a strong view either way, and I would think so long as we're consistent and the definition is also clear to patients, that either approach is reasonable. 

There are perhaps two ways of looking at how the DVT codes should relate to PE risk, depending on time frames:
- If we're asking about a recent DVT (eg last few months) we'd want it to anatomically have potential to lead to a PE (e.g. mesenteric but not portal).
- "DVT ever" should share risk factors with a future DVT that could lead to a PE. Assuming we're asking about any history of DVT/PE ever, then perhaps we are more interested in whether the previous DVT indicates that the person would be at increased risk of a future DVT and PE if they have COVID-19, than whether they could anatomically have had a PE from the previous DVT? In that case, perhaps it'd be reasonable to include cerebral, portal and mesenteric thrombosis as indicating some tendency to form clots in veins? (Concern that cerebral, portal and mesenteric thrombosis might be driven by local inflammation and hence less good indicators of a risk of future PE was the reason for my hesitation on this - but I think there's a reasonable case either way).

(5) For pregnancy would someone who had a history of a DVT/PE in pregnancy be likely to be at increased risk of PE if they contract COVID? If so, I'd be inclined to keep them in the codelist and simply ask about 'DVT/PE ever' without specifying that it was outside of pregnancy. (As an aside it might not be possible to reliably exclude DVT/PE in pregnancy, if not all episodes of DVT/PE in pregnancy specify pregnancy in the code - though I'd have expected that most would?) I don't think the risk tool will be designed to apply to women who are currently pregnant - it might be something to add to the caveats, @StatsFizz and @johntaz ?

Another consideration is how we will ask about this risk factor for the risk prediction tool. There's a pragmatic argument that asking about 'clots in legs or lungs' might be clearer than trying explain 'clots in veins but not arteries' for cerebral venous thrombosis but not stroke - in which case we might not want to include the cerebral, portal and mesenteric venous thromboses.

**Comment by hmcd** [comment]
Discussed today with @amirmehrkar @laurietomlinson and @johntaz 

**Summary of discussion**
The rationale for including DVT/PE in the risk prediction model, is that among individuals with a COVID-19 infection, an individual with a history of venous thrombosis may be at higher risk than the general population of a venous thromboembolic event (such as cerebral venous thrombosis or PE) which could increase the risk of mortality from COVID-19 infection.

For the risk prediction tool, the variable definition needs to correspond to a question that can be answered by an individual as a self-report. We thought a sensible question for the risk prediction tool would be:
"Have you ever had a clot in your veins, such as a deep vein thrombosis (DVT) or pulmonary embolism (PE)?

We agreed to include a history of venous clot in any location (including cerebral venous thrombosis, portal thrombosis and mesenteric thrombosis) , as a history of venous thrombosis in any location could indicate that the individual is likely to have an increased risk of a future venous thrombosis during a COVID-19 infection.

We agreed not to restrict based on the context in which it occurred. Past DVTs/PEs which occurred in the context of a temporary risk factor may be less strongly associated with future risk of venous thrombosis than other DVTs/PEs. Mostly, we can't identify the context of the DVT/PE. Some of the codes do specify that a DVT/PE occurred during pregnancy. However, we could not be confident that all DVTs/PEs which had occurred in pregnancy would be coded with a code specifying the context of pregnancy, and so we couldn't reliably exclude DVTs/PEs which occurred in pregnancy. In addition, a history of DVT/PE during a pregnancy is likely to indicate a somewhat increased risk of venous thrombosis during a COVID-19 infection compared to the general population, even when no longer pregnant.

DEFINITION: A history of venous thromboembolic disease

Variables:
(1) a binary variable denoting the presence of one of the codes at any point in the patient record.
(2) the earliest date of such a code.

CODE LISTS:

Process
(1) Read 2 code list from Helen Strongman and Angel Wong combined here:
We did not include codes for suspected/possible DVT/PE;  nor PEs specified as air embolism or amniotic fluid embolism as would not indicate at ongoing risk of a venous clot.
(2) SNOMED searched for DVT and PE
- didn't include air embolisms, fat embolisms, or amniotic fluid embolisms or suspected PE
- assumed unspecified PEs were blood clots.
(3) mapped to CTV3 and reviewed by Helen McDonald and Amir Mehrkar, principles discussed with Laurie Tomlinson as above.
To reflect the conversation, HM updated the spreadsheet with a final recommendation
[CTV3_venous_thromboembolism_combining_comments.xlsx](https://github.com/opensafely/codelist-development/files/5190649/CTV3_venous_thromboembolism_combining_comments.xlsx)


FLEXIBILITY NEEDED BETWEEN STUDIES: 
This list 
- doesn't include fat pulmonary embolism, air pulmonary embolism or amniotic fluid pulmonary embolism (though assumes unspecified PEs are thromboembolic)
- includes codes for any history of DVT or PE - studies of incident DVT/PE may wish to exclude these. 
- includes codes for PE/DVT in pregnancy, which may not be relevant for all studies
- includes codes for cerebral venous thrombosis (which may be caused by cerebral inflammation eg. meningitis and is only very rarely associated with PE) and portal thrombosis (which may be caused by liver pathology and should not be able to result in PE) and mesenteric thrombosis, not all of which may be relevant for other study questions.

EFFECTS ON COHORT SELECTION: None

POTENTIAL BIASES: This variable includes a history of any venous thrombosis. Some DVTs/PEs will have occurred in the context of a temporary condition (e.g. pregnancy, meningitis, immobility), and some individuals identified by this codelist will be at higher risk of future DVT/PE than others. 

FINAL CLEAN CODELIST
[CTV3_venous_thromboembolism_final.xlsx](https://github.com/opensafely/codelist-development/files/5190650/CTV3_venous_thromboembolism_final.xlsx)

Signed off
Epidemiologist Helen McDonald 08/09/2020 20:40
Clinical

**Comment by hmcd** [comment]
@amir @laurie @johntaz hope the above summarises the discussion- please do edit if not! @amirmehrkar if you're happy with the codelist would you be happy to sign off?

**Comment by amirmehrkar** [comment]
Just to be clear - on the xls for the "FINAL CLEAN CODELIST" - we will be including all all 1, P and C in column D.

**Comment by hmcd** [comment]
Ah, we need to remove the codes that we don't want to be using from the final clean codelist - sorry, I thought I had done this. Amir, did you change any code decisions, or can I just upload the file I have?

**Comment by amirmehrkar** [comment]
I didnt change your code decisions in Column D - I just made my comments. Hence 1 + P + C = inclusion list as I understand it.

**Comment by hmcd** [comment]
Fab, then the codelist is 
[CTV3_venous_thromboembolism_final_clean.xlsx](https://github.com/opensafely/codelist-development/files/5200596/CTV3_venous_thromboembolism_final_clean.xlsx)

**Comment by johntaz** [comment]
Thanks everyone - I agree with your summary and will upload to the codelists website
