### ISSUE TITLE
Disease: Atrial Fibrillation Clinical Finding

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#37]
WE have a variety of clinical codes related to atrial fibrillation on OpenCodelists. This codelist is intended to solely identify where there has been a "clinical finding" of atrial fibrillation or similar. This should mirror the QoF register in practices and those eligible for anticoagulation.

CTV3Code | Description
-- | --
G573. | Atrial fibrillation and flutter
G5730 | Atrial fibrillation
G5731 | Atrial flutter
G573z | Atrial fibrillation and flutter NOS
X202R | Lone atrial fibrillation
X202S | Non-rheumatic atrial fibrillation
Xa2E8 | Paroxysmal atrial fibrillation
Xa7nI | Controlled atrial fibrillation
XaEga | Rapid atrial fibrillation
XaOfa | Persistent atrial fibrillation
XaOft | Permanent atrial fibrillation
XaaUH | Paroxysmal atrial flutter
XaeUP | Chronic atrial fibrillation
XaeUQ | Typical atrial flutter
XaeUR | Atypical atrial flutter

**Comment by brianmackenna** [comment]
@amirmehrkar has reviewed this list and agrees it is good to go but has a question about why `G5732 paroxysmal atrial fibrillation` is not included.

I've had a quick look into this with @inglesp  and it appears that `G5732` has been deprecated and is covered by `XaaUH`. If this was another disease we may wish to check records for deprecated codes or check on mapping methodology however as AF is on the main QoF registers I'm sure this work has been done and codelist is good to go.

**Comment by brianmackenna** [comment]
@amirmehrkar I have added to OpenCodelists. Do you want to give quick check to see if happy with description?

https://codelists.opensafely.org/codelist/opensafely/atrial-fibrillation-clinical-finding/2020-07-09/#tree

**Comment by amirmehrkar** [comment]
@brianmackenna yep all makes sense. Happy with description and rationale. Thanks
