### ISSUE TITLE
*Condition* Transient ischaemic attack

### ISSUE THREAD

**Issue by angelwong121** [opensafely/codelist-development#38]
Rationale of developing the codelist:
This is used for the anticoagulant use before COVID project. We will calculate the CHAD2S2-VASc score using codelists. One of the component is stroke/TIA but currently in OS the stroke codelist does not include codes for TIA, so will add a codelist specifically for TIA. It includes any codes indicating the person might have incident/history TIA.

URL of codelist builder: https://codelists.opensafely.org/builder/angel-wong/transient-ischaemic-attack/

Coding system: SNOMED CT
```
Keyword searched in codelist builder: 
transient cerebral ischaemia
transient ischaemic attack
h/o: tia
```

Before generating the codelist here, I excluded codes only indicating the assessment scale (CHAD2S2-VASc score itself), high risk of TIA, suspected case and family history of TIA.

The codelist for review: 
[angel-wong-transient-ischaemic-attack-2020-11-09T19-28-42.xlsx](https://github.com/opensafely/codelist-development/files/5516907/angel-wong-transient-ischaemic-attack-2020-11-09T19-28-42.xlsx)

**Comment by laurietomlinson** [comment]
[angel-wong-transient-ischaemic-attack-2020-11-09T19-28-42_LT.xlsx](https://github.com/opensafely/codelist-development/files/5625859/angel-wong-transient-ischaemic-attack-2020-11-09T19-28-42_LT.xlsx)

Rationale: I have excluded codes which were stroke/TIA but it depends on how specific you want the included cases to be: if you would rather capture all TIAs at the risk of misclassifying stroke we should add them back in. This is also true of the 'syndrome' diagnoses. I have also  included 'history of' codes but if you want to capture incident outcomes you should remove these as well

**Comment by angelwong121** [comment]
Thanks @laurietomlinson 
As we will use this TIA codelist combined with the stroke codelist for calculating CHAD2S2-VASc score, we don't need to make sure they are definite TIA codes. For some codes that you excluded, they were already included in the stroke codelist so we can leave them out. However, I included some codes back (from rows 18-24) because they were not included in the stroke codelist. We can make a note in OS codelist webpage when we upload the codelist that some codes do not represent definite TIA.
I've attached the codelist with my minor comment:
[angel-wong-transient-ischaemic-attack-2020-11-09T19-28-42_LT_AW.xlsx](https://github.com/opensafely/codelist-development/files/5630449/angel-wong-transient-ischaemic-attack-2020-11-09T19-28-42_LT_AW.xlsx)

**Comment by angelwong121** [comment]
@inglesp , the above codelist is ready to be converted to CTV3

**Comment by angelwong121** [comment]
the codelist has converted to CTV3:
[angel-wong-transient-ischaemic-attack-2020-11-09T19-28-42_v2-ctv3.xlsx](https://github.com/opensafely/codelist-development/files/5659010/angel-wong-transient-ischaemic-attack-2020-11-09T19-28-42_v2-ctv3.xlsx)

I had a quick look and there seems no big issues after the conversion. It would be great if you can have a quick look. If you are happy with this, can you help sign it off too?

POTENTIAL BIASES / NOTE: We also included unspecific codes which might indicate stroke/TIA because we want to identify people with stroke/TIA. We will use the stroke codelist derived before in OpenSAFELY in addition to this one for CHAD2S2-VASc score. In future studies which might need definite TIA would need to develop another codelist.

CLINICAL SIGN OFF & DATE:

EPIDEMIOLOGY SIGN OFF & DATE: Angel Wong @angelwong121 8/12/2020 11:42

SHARED WITH WIDER TEAM: Yes

FINAL SIGN OFF DATE (and apply label):

**Comment by angelwong121** [comment]
Due to long string in SNOMED which would cause problem if we export the codelist as xlsx, I rechecked the code and will send the csv file to @inglesp for converting to CTV3 codes.

I've also re-screened the codes, and removed some codes which only indicated invitation for TIA monitoring:
More information here (only keep this here for documentation of comments for codes inclusion/exclusion):
[angel-wong-transient-ischaemic-attack-2020-11-09T19-28-42_LT_AW.xlsx](https://github.com/opensafely/codelist-development/files/5674158/angel-wong-transient-ischaemic-attack-2020-11-09T19-28-42_LT_AW.xlsx)

**Comment by angelwong121** [comment]
Attached the final version after converting to CTV3:
[angel-wong-transient-ischaemic-attack-2a5be2d4-ctv3.csv.txt](https://github.com/opensafely/codelist-development/files/5702320/angel-wong-transient-ischaemic-attack-2a5be2d4-ctv3.csv.txt)
