### ISSUE TITLE
*Disease* Antiphospholipid syndrome

### ISSUE THREAD

**Issue by angelwong121** [opensafely/codelist-development#39]
Rationale of developing the codelist:
This is used for the anticoagulant use before COVID project. We will exclude people who had antiphospholipid syndrome in the analysis comparing warfarin and DOAC users because DOAC is not indicated for antiphospholipid syndrome. It includes any codes indicating the person might have incident/history antiphospholipid syndrome.

URL of codelist builder: https://codelists.opensafely.org/builder/angel-wong/antiphospholipid-syndrome/

Coding system: SNOMED CT

Keyword searched in codelist builder: 
```
antiphospholipid syndrome
hughes syndrome
```
Before generating the codelist here, I excluded codes indicating: X-linked intellectual disability, hypogonadism, ichthyosis, obesity, short stature syndrome

The codelist for review:
[angel-wong-antiphospholipid-syndrome-2020-11-09T18-34-08.xlsx](https://github.com/opensafely/codelist-development/files/5516952/angel-wong-antiphospholipid-syndrome-2020-11-09T18-34-08.xlsx)

**Comment by finersarah** [comment]
I have included "Lupus anticoagulant positive(878791000000101)". Lupus anticoagulant is synonymous with the detection of antiphospholipid antibodies which is seen in anti phospholipid syndrome. There are also some codes for lupus anticoagulant as a procedure - I don't think you need to include these as they just tell you the test has been done, not that it confirmed the condition.

**Comment by angelwong121** [comment]
Thanks @finersarah , I have created a new excel spreadsheet including the new code: "Lupus anticoagulant positive(878791000000101)"
Can you please review the codelist below:
[angel-wong-antiphospholipid-syndrome-2020-11-20T09-43-19.xlsx](https://github.com/opensafely/codelist-development/files/5572661/angel-wong-antiphospholipid-syndrome-2020-11-20T09-43-19.xlsx)

**Comment by finersarah** [comment]
Hi Angel,

Please see my review in the attached.

Sarah
[angel-wong-antiphospholipid-syndrome-2020-11-20T09-43-19_SF.xlsx](https://github.com/opensafely/codelist-development/files/5582382/angel-wong-antiphospholipid-syndrome-2020-11-20T09-43-19_SF.xlsx)

**Comment by angelwong121** [comment]
thanks @finersarah , @inglesp the codelist above is ready to be converted to CTV3 for further review

**Comment by angelwong121** [comment]
@laurietomlinson 
the codelist has converted to CTV3:
[angel-wong-antiphospholipid-syndrome-2020-11-20T09-43-19_SF-ctv3.xlsx](https://github.com/opensafely/codelist-development/files/5659004/angel-wong-antiphospholipid-syndrome-2020-11-20T09-43-19_SF-ctv3.xlsx)

I had a quick look and there seems no big issues after the conversion. It would be great if you can have a quick look. If you are happy with this, can you help sign it off too?

POTENTIAL BIASES / NOTE: None

CLINICAL SIGN OFF & DATE:

EPIDEMIOLOGY SIGN OFF & DATE: Angel Wong @angelwong121 8/12/2020 11:36

SHARED WITH WIDER TEAM: Yes

FINAL SIGN OFF DATE (and apply label):

**Comment by angelwong121** [comment]
Due to the string formatting in excel, re-attached the final codelist after converting to ctv3:
[angel-wong-antiphospholipid-syndrome-114c6f9f-ctv3.csv.txt](https://github.com/opensafely/codelist-development/files/5702329/angel-wong-antiphospholipid-syndrome-114c6f9f-ctv3.csv.txt)
