### ISSUE TITLE
*Disease* Peripheral artery disease

### ISSUE THREAD

**Issue by angelwong121** [opensafely/codelist-development#41]
Rationale of developing the codelist:
This is used for the anticoagulant use before COVID project. We will calculate the CHAD2S2-VASc score using codelists. One of the component is peripheral artery disease but currently in OS the peripheral artery disease codelist only include surgical codes, so will add all the diagnostic codes for PAD. It includes any codes indicating the person might have incident/history PAD.

URL of codelist builder: https://codelists.opensafely.org/builder/angel-wong/peripheral-artery-disease/

Coding system: SNOMED CT

Keyword searched in codelist builder: 
```
arterial insufficiency
arterial leg ulcer
claudication
intermittent claudication
claudication distance
embolism and thrombosis of an arm
embolism and thrombosis of an arm or leg artery
extremity artery atheroma
ischaemic foot
ischaemic leg ulcer
mixed venous and arterial leg ulcer
peripheral artery disease
peripheral circulatory failure
peripheral ischaemia
peripheral ischaemic vascular disease
peripheral vascular disease

```

Before generating the codelist here, I excluded codes only indicating the assessment scale, codes relating to brain (e.g. basilar artery syndrome, carotid artery insufficiency syndrome, vertebral artery syndrome, vertebrobasilar artery syndrome), perinatal codes, shock, referral, monitoring and family history.

The codelist for review:
[angel-wong-peripheral-artery-disease-2020-11-09T19-25-58.xlsx](https://github.com/opensafely/codelist-development/files/5517061/angel-wong-peripheral-artery-disease-2020-11-09T19-25-58.xlsx)

**Comment by angelwong121** [comment]
Helen McDonald worked on the codelist for Peripheral vascular disease: #24 [https://github.com/opensafely/codelist-development/issues/24#issuecomment-665595989](url)
Note: DVT codes were excluded from the list

The SNOMED and Read codes for PAD were converted to CTV3 from Chris according to #24 
Need further review for anticoagulant project:
[CTV3_Raw_PAD.xlsx](https://github.com/opensafely/codelist-development/files/5607586/CTV3_Raw_PAD.xlsx)

**Comment by laurietomlinson** [comment]
[CTV3_Raw_PAD_LT.xlsx](https://github.com/opensafely/codelist-development/files/5625830/CTV3_Raw_PAD_LT.xlsx)

**Comment by angelwong121** [comment]
CODELISTS:

FINAL CTV3 codes (
[CTV3_Raw_PAD_v2.xlsx](https://github.com/opensafely/codelist-development/files/5642907/CTV3_Raw_PAD_v2.xlsx)
), converted by TPP, derived from the following process:
#24 derived by Helen M, Laurie, and Amir. 
this issue - CTV3 codes reviewed by Laurie

POTENTIAL BIASES: 

CLINICAL SIGN OFF & DATE: Laurie Tomlinson @laurietomlinson  4/12/2020 13:08

EPIDEMIOLOGY SIGN OFF & DATE: Angel Wong @angelwong121  4/12/2020 13:08

SHARED WITH WIDER TEAM: Yes

FINAL SIGN OFF DATE (and apply label) 4/12/2020
