### ISSUE TITLE
hazardous drinking

### ISSUE THREAD

**Issue by angelwong121** [opensafely/codelist-development#53]
Rationale of developing the codelist:
This is used for the anticoagulant use before COVID project. We will assess the pattern of hazardous alcohol use between exposure groups as a proxy for risky behaviour. It includes any codes indicating hazardous drinking (including current/ex-drinker).

URL of codelist builder: https://codelists.opensafely.org/codelist/user/angel-wong/hazardous-drinking/3c786eff/#full-list

Coding system: SNOMED CT

Keyword searched in codelist builder (reference from Kate Mansfield and Angel Wong's codelist for alcohol used in CPRD Aurum):

```
ah - alcoholic hepatitis
alcohol abuse
alcohol addiction
alcohol causing toxic effect
alcohol counselling
alcohol dependence
alcohol detoxification
alcohol hallucinosis
alcohol harm reduction program
alcohol induced
alcohol intoxication
alcohol misuse
alcohol problem
alcohol rehabilitation
alcohol relapse
alcohol treatment
alcohol twelve step program
alcohol withdrawal
alcohol-induced persisting dementia
alcohol-related disorder
alcoholic
alcoholic cirrhosis
alcoholic fatty liver disease
alcoholic liver
alcoholic myopathic syndrome
alcoholic myositis
alcoholic peripheral neuropathy
alcoholic polyneuropathy
alcoholic steatosis
alcoholics anonymous
alcoholism
amnesic syndrome due to alcohol
binge drinker
delirium tremens
dementia associated with alcoholism
dilated cardiomyopathy secondary to alcohol
dipsomania
drinks in morning to get rid of hangover
drunkenness
excessive alcohol
harmful alcohol use
hazardous alcohol use
heavy drinker
korsakov syndrome - alcoholic
poisoning by alcohol
pseudo-cushing syndrome due to alcohol
reduce alcohol
withdrawn from alcohol detoxification program
```

Before generating the codelist here, I excluded codes only indicating assessment scale, accidental poisoning, and family history.

**Comment by we1980** [comment]
https://codelists.opensafely.org/codelist/user/william-elson/hazardous-drinking/6ef5fab2/#tree

We reviewed the code list and found that searching the term 'alcohol' alone was a very sensitive way to capture all 'hazardous drinking' codes. It covered all relevant terms in the previous version above and captured significantly more terms. As it generated a lot of non-relevant codes quite a number needed to be filtered out (i.e. it was not very specific).

Some specific points:
We included:

- codes suggesting hazardous drinking behavior regardless of whether this represented acute or chronic problems with alcohol.
- We included terms that suggested there was previous alcohol tolerance
- We excluded terms where it cannot be concluded that there is a behavioral problem with alcohol e.g. "Diarrhea caused by alcohol intake"

**Comment by angelwong121** [comment]
Thanks @we1980 
I've screened the codes and agree with most of the codes should be included, but a few want to double check with you; not sure if they specified hazardous alcohol use or only indicate alcohol use:

163184002 | On examination - breath - alcohol smell
274776000 | Finding of alcohol in blood
441685000 | Ethanol in blood specimen above reference range

**Comment by we1980** [comment]
Yes I thought quite a bit about these. My logical for including them was as follows.

1. 163184002 | On examination - breath - alcohol smell
 I included this as I thought that this person was drunk (or had been drinking) prior to an appointment at GP surgery. It's not just a random person in the pub.

2. 274776000 | Finding of alcohol in blood - This person had a reason to have an alcohol blood test which meant probably there was a suspicion they had been drinking and driving possibly.

2. 441685000 | Ethanol in blood specimen above reference range - same as above

To be honest I'd be comfortable either way

**Comment by angelwong121** [comment]
Agree with all these thanks @we1980

**Comment by angelwong121** [comment]
thanks @inglesp 
@we1980 , the codes have been mapped to CTV3. I've uploaded the codes to codelist builder for your final review:
https://codelists.opensafely.org/codelist/user/angel-wong/hazardous-drinking-ctv3-review/5b4c0769/#full-list

I've also attached the mapping file from SNOMED to CTV3 for your information:
[william-elson-hazardous-drinking-6ef5fab2-mapping.csv.txt](https://github.com/opensafely/codelist-development/files/5866706/william-elson-hazardous-drinking-6ef5fab2-mapping.csv.txt)

For the column `is_assured`, it means: mappings from CTV3 concepts to SNOMED concepts where the mapping has been clinically assured if it indicated as `yes`

**Comment by we1980** [comment]
@angelwong121. I don't think any codes need to be removed. There are a couple that it is tempting to throw out as the code implies they could be of non-alcoholic cause, but on balance I would probably keep them e.g. 

- Cirrhosis: [florid] or [alcoholic]
- (Cirrhos &/or chron liver dis) or (alcoholic liver disease)

Overall though I think it is a good attempt to define people with hazardous drinking behavior. Worth pointing out one more time for the record that we are including (amongst others) codes that indicate: 

- acute alcohol issues: such as binge drinking, evidence of recent excessive drinking behavior without necessarily being alcoholic
- chronic alcohol issues current: i.e. current evidence 'alcoholic' drinking
- chronic alcohol issues previous: i.e. those who have been previously described as alcoholics. It's hard to distinguish these at times from current alcoholics (e.g. history of alcoholism), but on balance we have kept them.

**Comment by angelwong121** [comment]
Great thanks @we1980 , well noted. Can you help sign this off here:

CODELIST:

FINAL CTV3 codes (https://codelists.opensafely.org/codelist/user/angel-wong/hazardous-drinking-ctv3-review/5b4c0769/#full-list), converted by TPP, derived from the following process:

Details shown in this issue - CTV3 codes reviewed by William Elson

POTENTIAL BIASES: 
We aim to define people with hazardous drinking behavior. This include codes of:

- **acute alcohol issues**: such as binge drinking, evidence of recent excessive drinking behavior without necessarily being alcoholic
- **chronic alcohol issues current**: i.e. current evidence 'alcoholic' drinking
- **chronic alcohol issues previous**: i.e. those who have been previously described as alcoholics. It's hard to distinguish these at times from current alcoholics (e.g. history of alcoholism). If there is a need to differentiate ex-drinker and current-drinker, this codelist need to be revisited and reviewed.

CLINICAL SIGN OFF & DATE:

EPIDEMIOLOGY SIGN OFF & DATE: Angel Wong @angelwong121 26/01/2021 17:30

SHARED WITH WIDER TEAM: Yes

FINAL SIGN OFF DATE (and apply label)

**Comment by we1980** [comment]
> Great thanks @we1980 , well noted. Can you help sign this off here:
> 
> CODELIST:
> 
> FINAL CTV3 codes (https://codelists.opensafely.org/codelist/user/angel-wong/hazardous-drinking-ctv3-review/5b4c0769/#full-list), converted by TPP, derived from the following process:
> 
> Details shown in this issue - CTV3 codes reviewed by William Elson
> 
> POTENTIAL BIASES:
> We aim to define people with hazardous drinking behavior. This include codes of:
> 
> * **acute alcohol issues**: such as binge drinking, evidence of recent excessive drinking behavior without necessarily being alcoholic
> * **chronic alcohol issues current**: i.e. current evidence 'alcoholic' drinking
> * **chronic alcohol issues previous**: i.e. those who have been previously described as alcoholics. It's hard to distinguish these at times from current alcoholics (e.g. history of alcoholism). If there is a need to differentiate ex-drinker and current-drinker, this codelist need to be revisited and reviewed.
> 
> CLINICAL SIGN OFF & DATE: @we1980 26/01/2021 17:36
> 
> EPIDEMIOLOGY SIGN OFF & DATE: Angel Wong @angelwong121 26/01/2021 17:30
> 
> SHARED WITH WIDER TEAM: Yes
> 
> FINAL SIGN OFF DATE (and apply label)
