### ISSUE TITLE
HAS-BLED score

### ISSUE THREAD

**Issue by angelwong121** [opensafely/codelist-development#54]
Rationale of developing the codelist:
This is used for the anticoagulant use before COVID project. We will identify the recorded HAS-BLED score.

URL of codelist builder: https://codelists.opensafely.org/codelist/user/angel-wong/has-bled/0d0c488b/

Coding system: SNOMED CT

Keyword searched in codelist builder:
`has-bled score`

Before generating the codelist, I excluded the procedure code (Assessment using hypertension, abnormal renal/liver function, stroke, bleeding history or predisposition, labile international normalized ratio, elderly over 65, and drugs/alcohol concomitantly score).

**Comment by brianmackenna** [comment]
Sorry if this has been discussed elsewhere but......

Why was the procedure code excluded?


On the [NHS  term browser](https://termbrowser.nhs.uk/?perspective=full&conceptId1=794231000000107&edition=uk-edition&release=v20201125&server=https://termbrowser.nhs.uk/sct-browser-api/snomed&langRefset=999001261000000100,999000691000001104) there are 6 codes - should these be included also?

**Comment by angelwong121** [comment]
@brianmackenna This is open for discussion. I initially excluded the procedure code because i think it may only be a code indicating HAS-BLED was recorded instead of the score itself? Happy to include it back if this is not the case.

About other codes in NHS term browser - i additionally used the search term "has bled" but no additional codes can be identified. I would expect the other 3 codes are only children codes of these two codes? @inglesp any insight?

**Comment by angelwong121** [comment]
@CarolineMorton  as we discussed, we'll use CTV3 codes in the codelist.py so I wondered I should searched the codes in CTV3 in the codelist builder instead of SNOMED as usual?
Then we end up having one code only: https://codelists.opensafely.org/builder/67a46e5f/search/has-bled/

**Comment by angelwong121** [comment]
@inglesp , can you please help map the SNOMED codes here: https://codelists.opensafely.org/codelist/user/angel-wong/has-bled/423c9434/#tree
Just wanted to make sure we did not miss any CTV3 codes

**Comment by angelwong121** [comment]
After mapping to CTV3 from SNOMED, only one CTV3 code can be identified: 
[angel-wong-has-bled-423c9434-ctv3.csv.txt](https://github.com/opensafely/codelist-development/files/5869642/angel-wong-has-bled-423c9434-ctv3.csv.txt)
[angel-wong-has-bled-423c9434-mapping.csv.txt](https://github.com/opensafely/codelist-development/files/5869643/angel-wong-has-bled-423c9434-mapping.csv.txt)
