### ISSUE TITLE
*Medication* Rivaroxaban

### ISSUE THREAD

**Issue by speed-vm** [opensafely/codelist-development#56]
Rivaroxaban (Direct Oral Anticoagulant)

Codelist required for individual drug. Codelist for all DOACs already exists. 
https://codelists.opensafely.org/codelist/opensafely/direct-acting-oral-anticoagulants-doac/2020-10-05/

See link for rivaroxaban only codelist in excel
[opensafely-rivaroxaban-2021-01-15.xlsx](https://github.com/opensafely/codelist-development/files/5820417/opensafely-rivaroxaban-2021-01-15.xlsx)

Search terms "rivaroxaban" and "xarelto"

https://codelists.opensafely.org/builder/358587f5/search/rivaroxaban/

**Comment by brianmackenna** [comment]
@speed-vm I'm happy with this.

@inglesp will transfer to the OpenSAFELY org so anyone can reuse now.  Can you have a go at writing the metadata please?

One thing when naming on the website we should just call `rivaroxaban` (plus or minus medication at the end). Naming it same as this issue will call problems when people are writing the pyton study definitions

Feel free to crack on with other DOACs as well

**Comment by brianmackenna** [comment]
@speed-vm  we have moved to OpenSAFELY org for anyone to re-use. Just needs methodology now
https://codelists.opensafely.org/codelist/opensafely/rivaroxaban/358587f5/

**Comment by speed-vm** [comment]
Thank you Brian, I will have some time later in the week to complete the rest of DOACs, and will do riva methodology.

Vicky

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by richiecroker** [comment]
now signed off.

**Comment by brianmackenna** [comment]
Reopening as a couple of things
1. Only 1 sign off on OpenCodelists @richiecroker need to add @speed-vm 
2. I can only see a `bnf_code` list - we need to convert it to a dm+d codelist as this is what is needed to query the data. For the moment this is slightly manual. Please shout at me or @inglesp  if you need assistance!

**Comment by speed-vm** [comment]
Sorry both @brianmackenna @inglesp What exactly do you need me to do please? Thanks

**Comment by brianmackenna** [comment]
Don't worry @speed-vm  leave it with the DataLab team

**Comment by richiecroker** [comment]
DM+D version published https://codelists.opensafely.org/codelist/opensafely/rivaroxaban-dmd/1e58b82a/
