### ISSUE TITLE
*medication* edoxaban

### ISSUE THREAD

**Issue by speed-vm** [opensafely/codelist-development#58]
Edoxaban (Direct Oral Anticoagulant)

Codelist required for individual drug. Codelist for all DOACs already exists.
https://codelists.opensafely.org/codelist/opensafely/direct-acting-oral-anticoagulants-doac/2020-10-05/

See link for edoxaban only codelist in excel
[opensafely-edoxaban-2021-01-22.xlsx](https://github.com/opensafely/codelist-development/files/5855411/opensafely-edoxaban-2021-01-22.xlsx)

Search terms "edoxaban" and "lixiana"

https://codelists.opensafely.org/codelist/user/speed-vm/edoxaban/3cd71448/

**Comment by richiecroker** [comment]
Hi @speed-vm this is similar to #57 as there are no drug codes showing.

**Comment by speed-vm** [comment]
Hi Richard,

Apologies. I thought I had done the same as I had done for the rivaroxaban one.
How can I add the codes?

Sorry, I’m not sure whether Brian or somebody completed an additional step for me for rivaroxaban?

Thank you,

Vicky

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by richiecroker** [comment]
Hi, i'd just re-do the search for edoxaban and see if it appears!

**Comment by speed-vm** [comment]
https://codelists.opensafely.org/codelist/user/speed-vm/edoxaban/679b0562/

I think this has worked for edoxaban. Please let me know if you can see them? Thank you

**Comment by richiecroker** [comment]
Yep, i can see them.  If you save it so that it's not draft, i'll sign it off.

**Comment by richiecroker** [comment]
https://codelists.opensafely.org/codelist/opensafely/edoxaban-dmd/054944f5/
DM+D version created.
