### ISSUE TITLE
*medication* dabigatran

### ISSUE THREAD

**Issue by speed-vm** [opensafely/codelist-development#59]
Dabigatran (Direct Oral Anticoagulant)

Codelist required for individual drug. Codelist for all DOACs already exists.
https://codelists.opensafely.org/codelist/opensafely/direct-acting-oral-anticoagulants-doac/2020-10-05/

See link for dabigatran only codelist in excel
[opensafely-dabigatran-2021-01-22.xlsx](https://github.com/opensafely/codelist-development/files/5855505/opensafely-dabigatran-2021-01-22.xlsx)

Search terms "dabigatran" and "pradaxa"
https://codelists.opensafely.org/codelist/user/speed-vm/dabigatran/23c7a113/

**Comment by richiecroker** [comment]
@speed-vm this is also the same as #57

**Comment by speed-vm** [comment]
https://codelists.opensafely.org/codelist/user/speed-vm/dabigatran/4e8b922d/

Think the codes are on this one now, let me know if any problems. Thank you

**Comment by richiecroker** [comment]
@speed-vm if you save changes, rather than draft, i'll sign it off.

**Comment by speed-vm** [comment]
@richiecroker Is that the same as publish version?

I could see save changes when I was in the draft, but can't see that option now?

**Comment by richiecroker** [comment]
DM+D version published https://codelists.opensafely.org/codelist/opensafely/dabigatran-dmd/6c39d1bf/
