### ISSUE TITLE
*PATIENT*: ethnicity

### ISSUE THREAD

**Issue by sebbacon** [opensafely/codelist-development#7]
Useful for calculating eGFR and possibly when investigating ACE/ARB effects, but 

> if we can get it quickly great, but if it will delay things substantially I think we could live without it

And there are also data quality issues (to be described here... TPP will update us)

**Comment by Lextuga007** [comment]
Not an issue but I'm interested in seeing the ethnicity groupings that have been discussed here but the file attachments have all gone. I'm looking through opensafely/opencodelists but I hope you can direct me to a lookup (if there is one)? 

I'm trying to group up some of the Read Codes for ethnicity or confirm where they can't do at all. African - ethnic category 2001 census being a key one as it cannot be grouped to Black as it was also used as White and Mixed as I can confirm from other clinical systems.

**Comment by brianmackenna** [comment]
@Lextuga007 Apologies for the delay but I think we missed this with all the activity in August. Hope this helps? 


- our ethnicity list for CTV3 in TPP is available on https://codelists.opensafely.org/codelist/opensafely/ethnicity/2020-04-27/

 (also for OpenSAFELY team - closing now. We will   open a separate issue for ethnicity in Snomed)
