### ISSUE TITLE
Structured Medication review

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#70]
https://www.england.nhs.uk/wp-content/uploads/2020/09/SMR-Spec-Guidance-2020-21-FINAL-.pdf

https://codelists.opensafely.org/builder/5459205f/

**Comment by brianmackenna** [comment]
@richiecroker could you review please? https://codelists.opensafely.org/codelist/opensafely/structured-medication-review-nhs-england/5459205f/

**Comment by richiecroker** [comment]
done
