### ISSUE TITLE
*OTHER* Chronic obstructive pulmonary disease (COPD) annual review

### ISSUE THREAD

**Issue by richiecroker** [opensafely/codelist-development#75]
https://codelists.opensafely.org/codelist/user/richard-croker/chronic-obstructive-pulmonary-disease-copd-annual-review/410dd25f/

As per the asthma annual review - only "annual review" codes included.

**Comment by richiecroker** [comment]
New codelist based on QoF business rules https://codelists.opensafely.org/codelist/user/richard-croker/chronic-obstructive-pulmonary-disease-copd-review-qof/01cfd170/

**Comment by brianmackenna** [comment]
This looks good @richiecroker I can't seem to publish - can you save and publish please?

One questions arising - the quoted _refset_ of `760601000000107` - should I expect to see this in the SNOMED-CT browser as a refset?

**Comment by richiecroker** [comment]
refset is `999012691000230100`, but doesn't appear in term browser (as do not refsets, not sure why)

**Comment by richiecroker** [comment]
https://codelists.opensafely.org/codelist/user/richard-croker/chronic-obstructive-pulmonary-disease-copd-review-qof/01cfd170/ published
