### ISSUE TITLE
*OTHER* QRISK2 score

### ISSUE THREAD

**Issue by richiecroker** [opensafely/codelist-development#77]
https://codelists.opensafely.org/codelist/user/richard-croker/qrisk2-score/0c3c2bff/

Lots of codes with the same nomenclature.

**Comment by brianmackenna** [comment]
Have you checked to see what the defined codelist is in QoF business rules and how this might differ?

**Comment by richiecroker** [comment]
New codelist based on QoF rules (more than just QRISK2, including Framingham and QRISK3)
https://codelists.opensafely.org/codelist/user/richard-croker/cvd-risk-assessment-score-qof/1adf44a5/

**Comment by brianmackenna** [comment]
This matches the refset provided by NHS Digital so I am happy to sign off from that point of view.

To note I was very surprised to see the following included
- Framingham
- Joint British Society 2 (JBS2)

NICE et al when writing about QOF always say you must QRISK2 (and QRISK3 presumably) when estimating cvd risk. The [GMS contractual guidance of 2019](https://www.england.nhs.uk/wp-content/uploads/2019/05/gms-contract-qof-guidance-april-2019.pdf) does highlight the issue 

> NICE CG181 recommends QRISK2112, 113 as the risk assessment tool of choice in
patients aged between 25-84 years. However, the Business rules for this indicator
will also accept a risk assessment performed using the following additional tools - framingham, JB2 , qrisk 2, qrisk3

> QRISK3 is under development and will supersede QRISK2. Once QRISK3 is available, it will be
added to the Business Rules at the first opportunity.

**Comment by richiecroker** [comment]
Yes, it will be interesting to see how many of those codes show up.

**Comment by richiecroker** [comment]
https://codelists.opensafely.org/codelist/user/richard-croker/cvd-risk-assessment-score-qof/1adf44a5/
