### ISSUE TITLE
*MEDICINE* High Cost Drugs Adalimumab

### ISSUE THREAD

**Issue by AnnaB45** [opensafely/codelist-development#82]
I've created a list of the unique drug names for all adalimumab records in the high cost drugs dataset. 
The drug names are non-standardised, so not in dm+d or other standardised format. 
The list of drug names has been created by selecting all values that contain the string:
- adalimumab
- ADALIMUMAB
- Adalimumab

R code used to select drug names and csv output can be found in the following repos:
- [R code](https://github.com/opensafely/highcostdrugs-research/blob/study_def/analysis/creating_adalimumab_code_list.R)
- [csv list of drug names](https://github.com/opensafely/highcostdrugs-research/blob/study_def/codelists/code_list_adalimumab.csv)

**Comment by AnnaB45** [comment]
After review with @brianmackenna have decided to use the codelists as produced by Mark Yates and described in [this issue](https://github.com/opensafely/immunosuppressant-meds-research/issues/29).
Mark's code is more robust as doesn't rely on case of drug name and also searches on brand name as well as molecule.

**Comment by brianmackenna** [comment]
There'll need to be individual issues for each drug and describing methodology. Reopening this as I don't think there is a need for an individual adalimumab codelist in high cost drugs study. Or happy to close with another linked issue

**Comment by AnnaB45** [comment]
Going to use the drug name list that Mark created - as documented in [this issue](https://github.com/opensafely/immunosuppressant-meds-research/issues/29).
The specific csv for adalimumab is also attached.
This file has been uploaded as a draft codelist to [OpenSAFELY Codelists](https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-adalimumab/34b56b69/).
[adalimumab.xlsx](https://github.com/opensafely/codelist-development/files/6009982/adalimumab.xlsx)

**Comment by brianmackenna** [comment]
@AnnaB45 this looks good to me. For the methodolgy section I suggest we write in the exact strings from Marks query to make it transparent what we have used and the VMP that was assigned (I don't have example but think this might be important at some point for some anaylsis)

**Comment by AnnaB45** [comment]
Yes - methodology updated here: https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-adalimumab/34b56b69/

**Comment by brianmackenna** [comment]
https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-adalimumab/6eec91b5/
