### ISSUE TITLE
COVID19 vacc appointment DNA

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#93]
We need a codelist for vaccination "did not attends". There is likely to be distinct ones for each course plus generic DNAs

**Comment by brianmackenna** [comment]
First appointment
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-did-not-attend-first-appointment/300d360f/


Second appointment
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-did-not-attend-second-appointment/53e7a91c/


@HelenCEBM : Q should this actually be three seperate codelists with a code for the generic DNA `1240631000000102`

**Comment by HelenCEBM** [comment]
Two codelists is fine, I don't think a third would add much - they can be further distinguished where needed based on dates of events.

**Comment by brianmackenna** [comment]
Great  - happy with both of them?

**Comment by HelenCEBM** [comment]
Yes great 👍

**Comment by brianmackenna** [comment]
first 
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-did-not-attend-first-appointment/300d360f/

second
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-did-not-attend-second-appointment/53e7a91c/
