### ISSUE TITLE
COVID19 vacc allergy or contrindication

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#94]

**Comment by brianmackenna** [comment]
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-contraindication-or-allergy/3ad835e7/

**Comment by HelenCEBM** [comment]
Not sure we should include "abandoned" here - the reason for abandonment could be something else (e.g. declined)?

**Comment by brianmackenna** [comment]
Agree - remove. 

https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-contraindication-or-allergy/6b56e339/#full-list

**Comment by brianmackenna** [comment]
@HelenCEBM I think `SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) immunisation course not indicated 1324731000000105` fits here? agree

**Comment by HelenCEBM** [comment]
Yes I agree - I'm not sure if it might be used slightly differently sometimes (e.g. for temporary reasons like pregnancy or being too young?) but for now it fits fine in here.

**Comment by brianmackenna** [comment]
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-contraindication-or-allergy/2840c97c/

**Comment by HelenCEBM** [comment]
New version including inactive codes, some of which appear in clinical systems https://www.opencodelists.org/codelist/opensafely/covid-19-vaccination-contraindication-or-allergy/59f7a1a0/

**Comment by brianmackenna** [comment]
Looks good to me - we may need to think about guidance for including / excluding inactive codes more generally?

**Comment by HelenCEBM** [comment]
Yes it's particularly a problem when you search by code rather than words that it is easy to miss any inactive codes that may be relevant..
