### ISSUE TITLE
COVID-19 Vaccination Given

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#95]
This should include all codes from the [national reporting specification](https://codelists.opensafely.org/codelist/primis-covid19-vacc-uptake/covadm1/v1/) plus some others we have identified. Do you agree @HelenCEBM ?

**Comment by HelenCEBM** [comment]
Yes - this will capture any vaccine records recorded in SNOMED format and not accompanied by a typical record in the vaccine table

**Comment by HelenCEBM** [comment]
On second thought maybe this should exclude the ones that specify first and second dose, then this can be used in combination with the existing codelists and fit more easily into the existing study definition structure...?

**Comment by brianmackenna** [comment]
@HelenCEBM  what do you think?

https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-given/0f315647/

**Comment by HelenCEBM** [comment]
Great 👍 I added a little bit to the descriptive text.

**Comment by brianmackenna** [comment]
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-given/0f315647/
