### ISSUE TITLE
COVID-19 vaccination unavailable

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#96]

**Comment by brianmackenna** [comment]
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-unavailable/21c8c2b2/

**Comment by HelenCEBM** [comment]
👍

**Comment by brianmackenna** [comment]
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-unavailable/21c8c2b2/
