### ISSUE TITLE
COVID-19 vaccine dose not given

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#97]
First dose
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-first-dose-not-given/6fa9dc47/

Second dose
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-second-dose-not-given/569a6912/

Similar to DNAs #93  I have made two lists with generic code in each.

**Comment by HelenCEBM** [comment]
Should we include "not done" codes here as well? I'm not sure there is much discernible difference between not given and not done, and the numbers will likely be small.

**Comment by brianmackenna** [comment]
@HelenCEBM i have made a new list with all generic and first dose in the first one. The second dose just contains the second dose code and as per the table in gdoc marked as N/A.

First dose
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-first-dose-not-given/6fa9dc47/

Second dose
https://codelists.opensafely.org/codelist/opensafely/covid-19-vaccination-second-dose-not-given/3937fccf/

**Comment by HelenCEBM** [comment]
Thanks @brianmackenna that's fine as a way to split them, but I can't see the Not Done codes there, or do you think we should put them in a separate list?

**Comment by brianmackenna** [comment]
updated - do they look good?

**Comment by HelenCEBM** [comment]
Great - I'm wondering if Abandoned would fit too, potentially in the second dose one?

**Comment by brianmackenna** [comment]
Yep thats a good shout. I've included now.

**Comment by HelenCEBM** [comment]
We should also include this inactive code, found in relatively small numbers in records:
240681000000103 | Severe acute respiratory syndrome coronavirus 2 vaccination not done (situation)

**Comment by HelenCEBM** [comment]
https://www.opencodelists.org/codelist/opensafely/covid-19-vaccination-first-dose-not-given/786c94c1

**Comment by brianmackenna** [comment]
looks good to me
